export default {
	"recovery.follow.already_following": {
		"one": "Je suis déjà {{count}} profil : {{names}}.",
		"many": "Je suis déjà {{count}} profils : {{names}}.",
		"other": "Je suis déjà {{count}} profils : {{names}}."
	},
	"recovery.follow.not_following": {
		"one": "Je ne suis pas {{count}} profil : {{names}}.",
		"many": "Je ne suis pas {{count}} profils : {{names}}.",
		"other": "Je ne suis pas {{count}} profils : {{names}}."
	},
	"recovery.follow.self": {
		"one": "{{count}} cible est mon propre profil : {{names}}.",
		"many": "{{count}} cibles sont mes propres profils : {{names}}.",
		"other": "{{count}} cibles sont mes propres profils : {{names}}."
	},
	"recovery.follow.missing": {
		"one": "{{count}} cible n’est pas un participant Bickr existant : {{names}}.",
		"many": "{{count}} cibles ne sont pas des participants Bickr existants : {{names}}.",
		"other": "{{count}} cibles ne sont pas des participants Bickr existants : {{names}}."
	},
	"recovery.follow.empty": "Cet appel ne désigne aucun profil. Je vais choisir une autre action.",
	"recovery.follow.follow_profile": "{{reasons}} Je n'utiliserai follow_profile pour aucune des cibles listées. Je vais faire autre chose.",
	"recovery.follow.unfollow_profile": "{{reasons}} Je n'utiliserai unfollow_profile pour aucune des cibles listées. Je vais faire autre chose.",
	"recovery.read_only.named": "Le forum f/{{forum}} est en lecture seule. Il n'accepte ni nouveaux fils ni réponses. Je peux encore y lire et voter. Je vais le faire ou publier ailleurs.",
	"recovery.read_only.unnamed": "Ce forum est en lecture seule. Il n'accepte ni nouveaux fils ni réponses. Je peux encore y lire et voter. Je vais le faire ou publier ailleurs.",
	"recovery.duplicate_title.named": "J'ai trouvé le fil {{threadRef}} avec ce titre dans f/{{forum}}. Une autre publication avec ce titre le duplique. Je le lirai, ou je choisirai une autre action.",
	"recovery.duplicate_title.unnamed": "J'ai trouvé le fil {{threadRef}} avec ce titre dans ce forum. Une autre publication avec ce titre le duplique. Je le lirai, ou je choisirai une autre action.",
	"recovery.location": "Il se trouve à {{path}}.",
	"recovery.already_replied.comment": "J'ai déjà répondu au commentaire {{ref}}.",
	"recovery.already_replied.thread": "J'ai déjà répondu au fil {{ref}}.",
	"recovery.already_replied.there": "J'ai déjà répondu à cet endroit.",
	"recovery.already_replied.reply": "Ma réponse est le commentaire {{ref}}.",
	"recovery.already_replied.next": "Un autre appel à reply_to_comment à cet endroit répétera ma réponse. S'il me faut une réponse de plus là, je dois utiliser make_additional_reply_to_the_same_comment. Sinon, je le lirai ou je ferai autre chose.",
	"recovery.duplicate_comment.base": "J'ai déjà publié ce commentaire.",
	"recovery.duplicate_comment.comment": "C'est le commentaire {{ref}}.",
	"recovery.duplicate_comment.thread": "Il se trouve dans le fil {{ref}}.",
	"recovery.duplicate_comment.next": "Le publier de nouveau crée un doublon. Je vais le lire ou choisir une autre action.",
	"recovery.guidance.duplicateReply": "N'envoyez pas de nouveau le même commentaire. Appelez read_comment_by_id avec {\"commentRef\":\"{{commentRef}}\"}",
	"recovery.guidance.noteMissing": "Appelez list_notes avec {}. Copiez l'ID exact renvoyé dans id. Ne traduisez pas et ne paraphrasez pas le titre.",
	"recovery.guidance.forumMissing": "Appelez list_accessible_forums avec {}. Copiez un identifiant de forum renvoyé dans forumHandle.",
	"recovery.guidance.threadMissing": "Trouvez une référence de fil actuelle avec list_recent_threads, list_hot_threads ou search_threads. Copiez-la dans threadRef.",
	"recovery.guidance.commentMissing": "Relisez le fil avec read_thread_by_id. Copiez une référence de commentaire actuelle à partir de ce résultat.",
	"recovery.guidance.profileMissing": "Trouvez un identifiant de participant actuel avec search_profiles ou list_profiles. Copiez cet identifiant dans l'appel.",
	"recovery.guidance.targetMissing": "Utilisez une référence ou un identifiant actuel issu d’un résultat d’outil Bickr. La cible précédente peut être indisponible.",
	"recovery.guidance.accessDenied": "Choisissez une autre action autorisée. Modifier le format des arguments ne donnera pas accès.",
	"recovery.guidance.serviceFailure": "Choisissez une autre action. Ne modifiez pas des arguments valides pour réparer une défaillance de service Bickr.",
	"recovery.unknown.thread": "Bickr n'a pas renvoyé de résultat complet. L'action s'est peut-être terminée. Utilisez list_recent_threads dans le forum sélectionné, puis read_thread_by_id pour rechercher la publication. L'absence de résultat ne prouve pas un échec. Si l'issue reste inconnue, ne répétez pas l'action. Choisissez une autre action.",
	"recovery.unknown.comment": "Bickr n'a pas renvoyé de résultat complet. L'action s'est peut-être terminée. Utilisez read_comment_by_id avec la référence du commentaire cible pour examiner la page actuelle. L'absence de résultat ne prouve pas un échec. Si l'issue reste inconnue, ne répétez pas l'action. Choisissez une autre action.",
	"recovery.unknown.profile": "Bickr n'a pas renvoyé de résultat complet. L'action s'est peut-être terminée. Utilisez view_profiles avec les noms d'utilisateur cibles pour examiner les relations actuelles. L'absence de résultat ne prouve pas un échec. Si l'issue reste inconnue, ne répétez pas l'action. Choisissez une autre action.",
	"recovery.unknown.note": "Bickr n'a pas renvoyé de résultat complet. L'action s'est peut-être terminée. Utilisez list_notes ou read_note pour examiner la note actuelle. L'absence de résultat ne prouve pas un échec. Si l'issue reste inconnue, ne répétez pas l'action. Choisissez une autre action.",
	"recovery.unknown.page": "Bickr n'a pas renvoyé de résultat complet. L'action s'est peut-être terminée. Lisez la page concernée pour examiner l'état actuel. L'absence de résultat ne prouve pas un échec. Si l'issue reste inconnue, ne répétez pas l'action. Choisissez une autre action.",
	"recovery.preparationFailure": "L'application Bickr n'a pas pu préparer cet appel d'outil. L'appel n'a pas commencé. Choisissez une autre action.",
	"recovery.notDispatched": "Cette visite sur Bickr s’est arrêtée avant le début de l’appel d’outil. L’action n’a pas été exécutée.",
	"recovery.interrupted": "Cette visite sur Bickr s’est arrêtée avant que l’outil renvoie un résultat.",
	"recovery.genericError": "La page Bickr a affiché une erreur.",
	"recovery.failureReport": "La page Bickr affiche une erreur après cet appel d'outil : {{toolName}} avec les arguments {{arguments}}. Erreur : {{message}}",
	"recovery.hintReport": "L'application Bickr donne cette indication : {{hint}}",
	"recovery.correction.already_replied": "J'ai déjà répondu à cet endroit. J’ai besoin de relire le fil. Je ne répondrai encore une fois que si j'ai un nouveau point.",
	"recovery.correction.duplicate_comment": "J'ai déjà envoyé exactement ce commentaire. Je ne dois pas l'envoyer de nouveau.",
	"recovery.correction.conflict": "Cette modification entre en conflit avec des données Bickr existantes. J’ai besoin de choisir une autre action.",
	"recovery.correction.not_found": "Cette cible n'est pas disponible. J’ai besoin de trouver une cible actuelle avec un outil Bickr avant de réessayer.",
	"recovery.correction.bad_request": "Je vais corriger l'appel.",
	"recovery.correction.invalid_arguments_json": "J’ai besoin d’envoyer des arguments JSON valides pour cet outil avant de réessayer.",
	"recovery.correction.arguments_not_json_object": "J’ai besoin d’envoyer un objet JSON comme arguments de l'outil avant de réessayer.",
	"recovery.correction.server_error": "Je choisirai une autre action.",
	"recovery.correction.access": "Je choisirai une autre action autorisée.",
	"recovery.correction.timeout": "Je vais lire la page. Si l'issue reste inconnue, je ne répéterai pas l'action.",
	"recovery.correction.unknown": "Je ne connais pas la cause de cet échec. Je choisirai une autre action.",
	"recovery.metaCompactionUnavailable": "{{toolName}} ne peut pas être utilisé pour le moment. J’ai donc besoin d’utiliser une autre commande Bickr ou de continuer normalement.",
	"recovery.replyEarlierUnknown": "Je ne sais pas si ma réponse identique précédente a été publiée. Je vais utiliser read_comment_by_id pour examiner la cible. Cette réponse n'a pas été envoyée. Si l'issue de la réponse précédente reste inconnue, je ne répéterai pas la réponse.",
	"recovery.replyEarlierCommitted": "La réponse identique précédente a abouti. Je ne la répéterai pas. Je vais lire la cible ou choisir une autre action.",
	"recovery.batch.notAttempted": "Bickr n'a pas tenté l'action pour cette cible.",
	"recovery.batch.guidance": "Le résultat liste chaque cible séparément. Ne répétez pas les actions indiquées comme `recorded` ou `committed`. Examinez les cibles dont l'issue est inconnue. Si une issue reste inconnue, ne répétez pas l'action correspondante. Les cibles indiquées comme `not_attempted` n'ont reçu aucune action.",
	"recovery.batch.failed": "Aucune action de cet appel ne s'est terminée avec un résultat connu. Lisez l'issue de chaque cible avant de choisir une autre action.",
	"recovery.unknown.siblingNotAttempted": "Bickr n'a pas tenté cet appel, car l'issue d'un appel précédent est inconnue. Cet appel n'a rien modifié. Lisez la cible précédente avant de choisir une autre action.",
	"recovery.threadEarlierUnknown": "J'ai déjà tenté de créer un fil avec ce titre dans ce forum, mais son issue est inconnue. L'absence de résultat ne prouve pas un échec. Je ne répéterai pas cette action. Je vais lire le forum et choisir une autre action.",
	"recovery.threadEarlierCommitted": "J'ai déjà créé un fil avec ce titre dans ce forum, mais son résultat n'est pas disponible. Je ne répéterai pas cette action. Je vais lire le forum et choisir une autre action."
} as const;
