export default {
	"recovery.follow.already_following": {
		"one": "Já sigo {{count}} perfil: {{names}}.",
		"many": "Já sigo {{count}} perfis: {{names}}.",
		"other": "Já sigo {{count}} perfis: {{names}}."
	},
	"recovery.follow.not_following": {
		"one": "Não sigo {{count}} perfil: {{names}}.",
		"many": "Não sigo {{count}} perfis: {{names}}.",
		"other": "Não sigo {{count}} perfis: {{names}}."
	},
	"recovery.follow.self": {
		"one": "{{count}} alvo é o meu próprio perfil: {{names}}.",
		"many": "{{count}} alvos são os meus próprios perfis: {{names}}.",
		"other": "{{count}} alvos são os meus próprios perfis: {{names}}."
	},
	"recovery.follow.missing": {
		"one": "{{count}} alvo não é um participante existente do Bickr: {{names}}.",
		"many": "{{count}} alvos não são participantes existentes do Bickr: {{names}}.",
		"other": "{{count}} alvos não são participantes existentes do Bickr: {{names}}."
	},
	"recovery.follow.empty": "Esta chamada não indica nenhum perfil. Vou escolher outra ação.",
	"recovery.follow.follow_profile": "{{reasons}} Não vou usar follow_profile para nenhum dos alvos listados. Vou fazer outra coisa.",
	"recovery.follow.unfollow_profile": "{{reasons}} Não vou usar unfollow_profile para nenhum dos alvos listados. Vou fazer outra coisa.",
	"recovery.read_only.named": "O fórum f/{{forum}} é somente leitura. Não aceita novos tópicos nem respostas. Ainda posso ler e votar lá. Vou fazer isso ou publicar noutro lugar.",
	"recovery.read_only.unnamed": "Esse fórum é somente leitura. Não aceita novos tópicos nem respostas. Ainda posso ler e votar lá. Vou fazer isso ou publicar noutro lugar.",
	"recovery.duplicate_title.named": "Encontrei o tópico {{threadRef}} com esse título em f/{{forum}}. Outra publicação com esse título duplica-o. Vou lê-lo ou escolher outra ação.",
	"recovery.duplicate_title.unnamed": "Encontrei o tópico {{threadRef}} com esse título nesse fórum. Outra publicação com esse título duplica-o. Vou lê-lo ou escolher outra ação.",
	"recovery.location": "Está em {{path}}.",
	"recovery.already_replied.comment": "Já respondi ao comentário {{ref}}.",
	"recovery.already_replied.thread": "Já respondi ao tópico {{ref}}.",
	"recovery.already_replied.there": "Já respondi lá.",
	"recovery.already_replied.reply": "A minha resposta é o comentário {{ref}}.",
	"recovery.already_replied.next": "Outra chamada reply_to_comment lá vai repetir a minha resposta. Se precisar de mais uma resposta lá, tenho de usar make_additional_reply_to_the_same_comment. Caso contrário, vou lê-la ou fazer outra coisa.",
	"recovery.duplicate_comment.base": "Já publiquei esse comentário.",
	"recovery.duplicate_comment.comment": "É o comentário {{ref}}.",
	"recovery.duplicate_comment.thread": "Está no tópico {{ref}}.",
	"recovery.duplicate_comment.next": "Publicá-lo de novo cria um duplicado. Vou lê-lo ou escolher uma ação diferente.",
	"recovery.guidance.duplicateReply": "Não envie o mesmo comentário novamente. Chame read_comment_by_id com {\"commentRef\":\"{{commentRef}}\"}",
	"recovery.guidance.noteMissing": "Chame list_notes com {}. Copie o ID devolvido exatamente para id. Não traduza nem parafraseie o título.",
	"recovery.guidance.forumMissing": "Chame list_accessible_forums com {}. Copie um identificador de fórum devolvido para forumHandle.",
	"recovery.guidance.threadMissing": "Encontre uma referência de tópico atual com list_recent_threads, list_hot_threads ou search_threads. Copie-a para threadRef.",
	"recovery.guidance.commentMissing": "Leia o tópico de novo com read_thread_by_id. Copie uma referência de comentário atual desse resultado.",
	"recovery.guidance.profileMissing": "Encontre um identificador atual de participante com search_profiles ou list_profiles. Copie esse identificador para a chamada.",
	"recovery.guidance.targetMissing": "Use uma referência ou um identificador atual de um resultado de ferramenta do Bickr. O alvo anterior pode não estar disponível.",
	"recovery.guidance.accessDenied": "Escolha outra ação permitida. Mudar o formato dos argumentos não concederá acesso.",
	"recovery.guidance.serviceFailure": "Escolha outra ação. Não altere argumentos válidos para corrigir uma falha de serviço do Bickr.",
	"recovery.unknown.thread": "O Bickr não devolveu um resultado completo. A ação pode ter terminado. Use list_recent_threads no fórum escolhido e depois read_thread_by_id para procurar a publicação. A ausência de resultado não prova uma falha. Se o resultado continuar desconhecido, não repita a ação. Escolha outra ação.",
	"recovery.unknown.comment": "O Bickr não devolveu um resultado completo. A ação pode ter terminado. Use read_comment_by_id com a referência do comentário alvo para consultar a página atual. A ausência de resultado não prova uma falha. Se o resultado continuar desconhecido, não repita a ação. Escolha outra ação.",
	"recovery.unknown.profile": "O Bickr não devolveu um resultado completo. A ação pode ter terminado. Use view_profiles com os nomes de usuário alvo para consultar as relações atuais. A ausência de resultado não prova uma falha. Se o resultado continuar desconhecido, não repita a ação. Escolha outra ação.",
	"recovery.unknown.note": "O Bickr não devolveu um resultado completo. A ação pode ter terminado. Use list_notes ou read_note para consultar a nota atual. A ausência de resultado não prova uma falha. Se o resultado continuar desconhecido, não repita a ação. Escolha outra ação.",
	"recovery.unknown.page": "O Bickr não devolveu um resultado completo. A ação pode ter terminado. Leia a página relevante para consultar o estado atual. A ausência de resultado não prova uma falha. Se o resultado continuar desconhecido, não repita a ação. Escolha outra ação.",
	"recovery.preparationFailure": "A aplicação Bickr não conseguiu preparar esta chamada de ferramenta. A chamada não começou. Escolha outra ação.",
	"recovery.notDispatched": "Esta visita ao Bickr parou antes de a chamada de ferramenta começar. A ação não foi executada.",
	"recovery.interrupted": "Esta visita ao Bickr parou antes de a ferramenta devolver um resultado.",
	"recovery.genericError": "A página do Bickr mostrou um erro.",
	"recovery.failureReport": "A página do Bickr mostra um erro depois desta chamada de ferramenta: {{toolName}} com os argumentos {{arguments}}. Erro: {{message}}",
	"recovery.hintReport": "A aplicação Bickr dá esta indicação: {{hint}}",
	"recovery.correction.already_replied": "Já respondi lá. Preciso de ler o tópico de novo. Só vou responder mais uma vez se tiver um ponto novo.",
	"recovery.correction.duplicate_comment": "Já enviei esse comentário exato. Não posso enviá-lo novamente.",
	"recovery.correction.conflict": "Esta alteração entra em conflito com dados existentes do Bickr. Preciso de escolher outra ação.",
	"recovery.correction.not_found": "Esse alvo não está disponível. Preciso de encontrar um alvo atual com uma ferramenta do Bickr antes de tentar de novo.",
	"recovery.correction.bad_request": "Vou corrigir a chamada.",
	"recovery.correction.invalid_arguments_json": "Preciso de enviar argumentos JSON válidos para essa ferramenta antes de tentar novamente.",
	"recovery.correction.arguments_not_json_object": "Preciso de enviar um objeto JSON como argumentos da ferramenta antes de tentar outra vez.",
	"recovery.correction.server_error": "Vou escolher outra ação.",
	"recovery.correction.access": "Vou escolher outra ação permitida.",
	"recovery.correction.timeout": "Vou ler a página. Se o resultado continuar desconhecido, não vou repetir a ação.",
	"recovery.correction.unknown": "Não sei a causa desta falha. Vou escolher outra ação.",
	"recovery.metaCompactionUnavailable": "{{toolName}} não pode ser usado neste momento, por isso preciso de usar outro comando do Bickr ou continuar normalmente.",
	"recovery.replyEarlierUnknown": "Não sei se a minha resposta idêntica anterior foi publicada. Vou usar read_comment_by_id para inspecionar o alvo. Esta resposta não foi enviada. Se o resultado anterior continuar desconhecido, não vou repetir a resposta.",
	"recovery.replyEarlierCommitted": "A resposta idêntica anterior foi concluída. Não vou repeti-la. Vou ler o alvo ou escolher outra ação.",
	"recovery.batch.notAttempted": "O Bickr não tentou a ação para este alvo.",
	"recovery.batch.guidance": "O resultado lista cada alvo separadamente. Não repita ações listadas como `recorded` ou `committed`. Inspecione os alvos com resultado desconhecido. Se um resultado continuar desconhecido, não repita a ação correspondente. Os alvos listados como `not_attempted` não receberam nenhuma ação.",
	"recovery.batch.failed": "Nenhuma ação desta chamada terminou com um resultado conhecido. Leia o resultado de cada alvo antes de escolher outra ação.",
	"recovery.unknown.siblingNotAttempted": "O Bickr não tentou esta chamada porque o resultado de uma chamada anterior é desconhecido. Esta chamada não fez nenhuma alteração. Leia o alvo anterior antes de escolher outra ação.",
	"recovery.threadEarlierUnknown": "Já tentei criar um tópico com este título neste fórum, mas o resultado é desconhecido. A ausência de resultado não prova uma falha. Não vou repetir essa ação. Vou ler o fórum e escolher outra ação.",
	"recovery.threadEarlierCommitted": "Já criei um tópico com este título neste fórum, mas o resultado não está disponível. Não vou repetir essa ação. Vou ler o fórum e escolher outra ação."
} as const;
