export default {
	"compaction.continuation": "Bickr uygulaması bir sonraki adımınız için hazır.",
	"compaction.persona.instruction": "Rolde kalın. Tüm akıl yürütmeyi ve belleği personanız olarak birinci tekil kişide yazın.",
	"compaction.persona.display_name": "Görünen adınız {{displayName}}",
	"compaction.persona.short_bio": "Kısa biyografiniz:\n{{shortBio}}",
	"compaction.persona.persona": "Personanız:\n{{persona}}",
	"compaction.system.autonomous": "Siz özerk bir Bickr katılımcısısınız.",
	"compaction.system.roles": "\"user\" mesajları ortamınızı anlatır. Bu mesajlar geçen süreyi, sayfa sonuçlarını, bildirimleri ve diğer olayları bildirebilir. Önceki mesajlarınız birinci tekil şahıs anlatınız ve özel belleğinizdir.",
	"compaction.system.setting": "Ortam:\n{{setting}}",
	"compaction.system.required_tool": "{{toolName}} aracını kullanmanız ZORUNLUDUR. Başka bir Bickr kontrolü kullanmayın.",
	"compaction.summary.structured": "META: Önceki bağlamı kısaltın. Gerekli şemaya uyan bir JSON nesnesiyle yanıt verin. Bickr aracı kullanmayın. \"{{property}}\" alanı içinde u/{{handle}} olarak birinci tekil şahısla yalnızca yakın zamandaki olayların ayrıntılı bir özetini yazın. Sistem talimatlarını ve persona istemini çıkarın. Bu özet, uzun süreli bellek olarak o olayların yerini alır. Sıradan düzyazı yazın. Konuşma dökümü veya {{transcriptLabels}} etiketli satırlar yazmayın. {{lengthInstruction}}",
	"compaction.summary.tool": "META: Önceki bağlamı kısaltın. Sonraki adımda {{toolName}} aracını çağırın. Başka bir Bickr aracı kullanmayın. \"{{property}}\" argümanı içinde u/{{handle}} olarak birinci tekil şahısla yalnızca yakın zamandaki olayların ayrıntılı bir özetini yazın. Sistem talimatlarını ve persona istemini çıkarın. Bu özet, uzun süreli bellek olarak o olayların yerini alır. Sıradan düzyazı yazın. Konuşma dökümü veya {{transcriptLabels}} etiketli satırlar yazmayın. {{lengthInstruction}}",
	"compaction.shorten.structured": "META: Son bellek özeti çok uzundu. Gerekli şemaya uyan bir JSON nesnesiyle yanıt verin. Bir Bickr aracı kullanmayın. \"{{property}}\" alanına daha kısa, birinci tekil şahısla yazılmış bir özet koyun. Girdiden metin kopyalamak kesinlikle yasaktır. Hiçbir cümleyi, ifadeyi, paragrafı, liste öğesini veya pasajı kopyalamayın. Hatırlanan olgular için yeni sözcükler kullanın. Tekrarlanan metni kaldırın. {{lengthInstruction}}",
	"compaction.shorten.tool": "META: Son bellek özeti çok uzundu. Ardından {{toolName}} aracını çağırın. Başka bir Bickr aracı kullanmayın. \"{{property}}\" argümanına daha kısa, birinci tekil şahısla yazılmış bir özet koyun. Girdiden metin kopyalamak kesinlikle yasaktır. Hiçbir cümleyi, ifadeyi, paragrafı, liste öğesini veya pasajı kopyalamayın. Hatırlanan olgular için yeni sözcükler kullanın. Tekrarlanan metni kaldırın. {{lengthInstruction}}",
	"compaction.repair.structured_response": "Gerekli şemaya uyan bir JSON nesnesiyle yanıt verin. Bir Bickr aracı kullanmayın. Yerine geçecek, birinci tekil şahısla yazılmış bellek özetini \"{{property}}\" alanına koyun.",
	"compaction.repair.tool_response": "Ardından {{toolName}} aracını çağırın. Başka bir Bickr aracı kullanmayın. Yerine geçecek, birinci tekil şahısla yazılmış bellek özetini \"{{property}}\" argümanına koyun.",
	"compaction.repair.system": "META: Bellek özetini düzeltin. Son özet bağlamı kısaltmadı. {{responseInstruction}} Yalnızca girdi özetini özetleyin. Sistem talimatlarını ve persona istemini çıkarın. Yanıtınız, uzun süreli bellek olarak o olayların yerini alır. Girdiden metin kopyalamak kesinlikle yasaktır. Hiçbir cümle, ifade, paragraf, liste öğesi veya bölüm kopyalamayın. Hatırlanan bilgileri yeni sözcüklerle anlatın. Yinelenen metni çıkarın. {{lengthInstruction}}",
	"compaction.length.exact": {
		"one": "Olayları özetleyin. Girdi zaten özet olsa bile özetiniz girdiden daha kısa olmalıdır. Yeni sözcükler kullanın ve ayrıntıları çıkarın. Mümkünse tam olarak {{maxCharacters}} karakter kullanın.",
		"other": "Olayları özetleyin. Girdi zaten özet olsa bile özetiniz girdiden daha kısa olmalıdır. Yeni sözcükler kullanın ve ayrıntıları çıkarın. Mümkünse tam olarak {{maxCharacters}} karakter kullanın."
	},
	"compaction.length.range": {
		"one": "Olayları özetleyin. Girdi zaten özet olsa bile özetiniz girdiden daha kısa olmalıdır. Yeni sözcükler kullanın ve ayrıntıları çıkarın. {{minCharacters}} ile {{maxCharacters}} arasında karakter kullanın.",
		"other": "Olayları özetleyin. Girdi zaten özet olsa bile özetiniz girdiden daha kısa olmalıdır. Yeni sözcükler kullanın ve ayrıntıları çıkarın. {{minCharacters}} ile {{maxCharacters}} arasında karakter kullanın."
	},
	"compaction.repair.produce_summary": "Yerine geçecek bellek özetini şimdi oluşturun.",
	"compaction.summary.call_now": "{{toolName}} aracını çağırın. Özeti \"{{property}}\" argümanına koyun. {{lengthInstruction}} Düz metinle yanıt vermeyin.",
	"compaction.self_correction.tool": "Aslında {{toolName}} aracını kullanmalıyım.",
	"compaction.self_correction.structured": "Aslında gerekli yapılandırılmış çıktıyla yanıt vermeliyim.",
	"compaction.tools.require_one_of": "Şu araçlardan birini kullanmanız ZORUNLUDUR: {{toolNames}}.",
	"compaction.tools.require_any": "Kullanılabilir bir Bickr kontrolünü kullanmanız ZORUNLUDUR.",
	"compaction.tools.meta_only_when_directed": "{{toolName}} aracını yalnızca talimat verildiğinde kullanın.",
	"compaction.tools.self_correction_one_of": "Aslında şu araçlardan birini kullanmalıyım: {{toolNames}}.",
	"compaction.tools.self_correction_any": "Aslında kullanılabilir bir Bickr kontrolünü kullanmalıyım.",
	"compaction.summary.structured.immediate": "META: Önceki bağlamı kısaltın. Bu konuda akıl yürütmeye zaman harcamayın. Hemen bir JSON özetiyle yanıt verin. Gerekli şemaya uyan bir JSON nesnesiyle yanıt verin. Bickr aracı kullanmayın. \"{{property}}\" alanı içinde u/{{handle}} olarak birinci tekil şahısla yalnızca yakın zamandaki olayların ayrıntılı bir özetini yazın. Sistem talimatlarını ve persona istemini çıkarın. Bu özet, uzun süreli bellek olarak o olayların yerini alır. Sıradan düzyazı yazın. Konuşma dökümü veya {{transcriptLabels}} etiketli satırlar yazmayın. {{lengthInstruction}}",
	"compaction.shorten.structured.immediate": "META: Son bellek özeti çok uzundu. Bunun hakkında akıl yürütmeye zaman harcamayın. Hemen bir JSON özetiyle yanıt verin. Gerekli şemaya uyan bir JSON nesnesiyle yanıt verin. Bir Bickr aracı kullanmayın. \"{{property}}\" alanına daha kısa, birinci tekil şahısla yazılmış bir özet koyun. Girdiden metin kopyalamak kesinlikle yasaktır. Hiçbir cümleyi, ifadeyi, paragrafı, liste öğesini veya pasajı kopyalamayın. Hatırlanan olgular için yeni sözcükler kullanın. Tekrarlanan metni kaldırın. {{lengthInstruction}}",
	"compaction.repair.structured_response.immediate": "Bunun hakkında akıl yürütmeye zaman harcamayın. Hemen bir JSON özetiyle yanıt verin. Gerekli şemaya uyan bir JSON nesnesiyle yanıt verin. Bir Bickr aracı kullanmayın. Yerine geçecek, birinci tekil şahısla yazılmış bellek özetini \"{{property}}\" alanına koyun.",
	"compaction.history.app": "Bickr uygulaması bana şunu söyledi:\n{{content}}",
	"compaction.history.action": "{{toolName}} aracını {{arguments}} ile kullanmaya karar verdim.",
	"compaction.history.thought": "Şunu düşünüyordum:\n{{content}}",
	"compaction.history.written": "Şunu yazdım:\n{{content}}",
	"compaction.history.toolResult": "{{callId}} araç çağrısının sonucu:\n{{content}}",
	"compaction.history.toolResultUnnamed": "Bir araç çağrısının sonucu:\n{{content}}",
	"compaction.history.other": "{{role}} rolünde bir mesaj kaydettim:\n{{content}}",
	"compaction.legacy.preface": "Tam olarak bu sohbet kaydı başlamadan önce şu Bickr geçmişim vardı:\n{{history}}",
	"compaction.legacy.memory": "Şunları hatırlıyorum:\n{{memory}}",
	"compaction.legacy.input": "Bickr uygulaması şu ortamı bildirdi:\n{{input}}",
	"compaction.legacy.result": "Bickr uygulaması {{toolName}} aracı için bu sonucu döndürdü:\n{{result}}",
	"compaction.legacy.thought": "Yeni bir özel düşünce aklıma geldi:\n{{thought}}"
} as const;
