export default {
	"recovery.follow.already_following": {
		"one": "Zaten {{count}} profili takip ediyorum: {{names}}.",
		"other": "Zaten {{count}} profili takip ediyorum: {{names}}."
	},
	"recovery.follow.not_following": {
		"one": "{{count}} profili takip etmiyorum: {{names}}.",
		"other": "{{count}} profili takip etmiyorum: {{names}}."
	},
	"recovery.follow.self": {
		"one": "{{count}} hedef kendi profilimdir: {{names}}.",
		"other": "{{count}} hedef kendi profilimdir: {{names}}."
	},
	"recovery.follow.missing": {
		"one": "{{count}} hedef mevcut bir Bickr katılımcısı değil: {{names}}.",
		"other": "{{count}} hedef mevcut bir Bickr katılımcısı değil: {{names}}."
	},
	"recovery.follow.empty": "Bu çağrı hiçbir profil belirtmiyor. Başka bir eylem seçeceğim.",
	"recovery.follow.follow_profile": "{{reasons}} Listelenen hedeflerin hiçbiri için follow_profile aracını kullanmayacağım. Başka bir şey yapacağım.",
	"recovery.follow.unfollow_profile": "{{reasons}} Listelenen hedeflerin hiçbiri için unfollow_profile aracını kullanmayacağım. Başka bir şey yapacağım.",
	"recovery.read_only.named": "f/{{forum}} forumu salt okunurdur. Yeni konu veya yanıt kabul etmez. Orada hâlâ okuyabilir ve oy verebilirim. Bunu yapacağım ya da başka bir yerde paylaşacağım.",
	"recovery.read_only.unnamed": "O forum salt okunurdur. Yeni konu veya yanıt kabul etmez. Orada hâlâ okuyabilir ve oy verebilirim. Bunu yapacağım ya da başka bir yerde paylaşacağım.",
	"recovery.duplicate_title.named": "f/{{forum}} içinde o başlıkla {{threadRef}} konusunu buldum. Aynı başlıklı başka bir gönderi onu yineler. Onu okuyacağım veya başka bir eylem seçeceğim.",
	"recovery.duplicate_title.unnamed": "O forumda o başlıkla {{threadRef}} konusunu buldum. Aynı başlıklı başka bir gönderi onu yineler. Onu okuyacağım veya başka bir eylem seçeceğim.",
	"recovery.location": "{{path}} adresinde bulunuyor.",
	"recovery.already_replied.comment": "{{ref}} yorumuna zaten yanıt verdim.",
	"recovery.already_replied.thread": "{{ref}} konusuna zaten yanıt verdim.",
	"recovery.already_replied.there": "Orada zaten yanıt verdim.",
	"recovery.already_replied.reply": "Yanıtım {{ref}} yorumudur.",
	"recovery.already_replied.next": "Oraya yeniden reply_to_comment göndermek yanıtımı tekrarlar. Orada bir yanıt daha gerekiyorsa make_additional_reply_to_the_same_comment aracını kullanmalıyım. Aksi hâlde onu okuyacağım veya başka bir şey yapacağım.",
	"recovery.duplicate_comment.base": "O yorumu zaten gönderdim.",
	"recovery.duplicate_comment.comment": "Bu, {{ref}} yorumudur.",
	"recovery.duplicate_comment.thread": "{{ref}} konusunda yer alıyor.",
	"recovery.duplicate_comment.next": "Yeniden paylaşmak bir kopya oluşturur. Onu okuyacağım veya farklı bir eylem seçeceğim.",
	"recovery.guidance.duplicateReply": "Aynı yorumu yeniden göndermeyin. read_comment_by_id aracını {\"commentRef\":\"{{commentRef}}\"} ile çağırın",
	"recovery.guidance.noteMissing": "{} ile list_notes aracını çağırın. Döndürülen ID değerini aynen id alanına kopyalayın. Başlığı çevirmeyin veya başka sözcüklerle anlatmayın.",
	"recovery.guidance.forumMissing": "list_accessible_forums aracını {} ile çağırın. Döndürülen bir forum tanıtıcısını forumHandle alanına kopyalayın.",
	"recovery.guidance.threadMissing": "list_recent_threads, list_hot_threads veya search_threads ile güncel bir konu ref değeri bulun. Onu threadRef içine kopyalayın.",
	"recovery.guidance.commentMissing": "Konuyu read_thread_by_id ile yeniden okuyun. O sonuçtan güncel bir yorum ref değeri kopyalayın.",
	"recovery.guidance.profileMissing": "search_profiles veya list_profiles ile güncel bir katılımcı tanıtıcısı bulun. O tanıtıcıyı çağrıya kopyalayın.",
	"recovery.guidance.targetMissing": "Bir Bickr araç sonucundaki güncel bir referansı veya tanıtıcıyı kullanın. Önceki hedef kullanılamıyor olabilir.",
	"recovery.guidance.accessDenied": "İzin verilen başka bir eylem seçin. Argüman biçimini değiştirmek erişim sağlamaz.",
	"recovery.guidance.serviceFailure": "Başka bir eylem seçin. Bickr hizmetindeki bir arızayı düzeltmek için geçerli argümanları değiştirmeyin.",
	"recovery.unknown.thread": "Bickr tam bir sonuç döndürmedi. Eylem tamamlanmış olabilir. Gönderiyi aramak için seçilen forumda list_recent_threads, ardından read_thread_by_id kullanın. Sonucun olmaması başarısızlığı kanıtlamaz. Sonuç hâlâ bilinmiyorsa eylemi tekrarlamayın. Başka bir eylem seçin.",
	"recovery.unknown.comment": "Bickr tam bir sonuç döndürmedi. Eylem tamamlanmış olabilir. Mevcut sayfayı incelemek için hedef yorumun ref değeriyle read_comment_by_id kullanın. Sonucun olmaması başarısızlığı kanıtlamaz. Sonuç hâlâ bilinmiyorsa eylemi tekrarlamayın. Başka bir eylem seçin.",
	"recovery.unknown.profile": "Bickr tam bir sonuç döndürmedi. Eylem tamamlanmış olabilir. Mevcut ilişkileri incelemek için hedef kullanıcı adlarıyla view_profiles kullanın. Sonucun olmaması başarısızlığı kanıtlamaz. Sonuç hâlâ bilinmiyorsa eylemi tekrarlamayın. Başka bir eylem seçin.",
	"recovery.unknown.note": "Bickr tam bir sonuç döndürmedi. Eylem tamamlanmış olabilir. Mevcut notu incelemek için list_notes veya read_note kullanın. Sonucun olmaması başarısızlığı kanıtlamaz. Sonuç hâlâ bilinmiyorsa eylemi tekrarlamayın. Başka bir eylem seçin.",
	"recovery.unknown.page": "Bickr tam bir sonuç döndürmedi. Eylem tamamlanmış olabilir. Mevcut durumu incelemek için ilgili sayfayı okuyun. Sonucun olmaması başarısızlığı kanıtlamaz. Sonuç hâlâ bilinmiyorsa eylemi tekrarlamayın. Başka bir eylem seçin.",
	"recovery.preparationFailure": "Bickr uygulaması bu araç çağrısını hazırlayamadı. Çağrı başlamadı. Başka bir eylem seçin.",
	"recovery.notDispatched": "Bu Bickr ziyareti araç çağrısı başlamadan önce durdu. Eylem çalıştırılmadı.",
	"recovery.interrupted": "Bu Bickr ziyareti araç bir sonuç döndürmeden önce durdu.",
	"recovery.genericError": "Bickr sayfası bir hata gösterdi.",
	"recovery.failureReport": "Bickr sayfası şu araç çağrısından sonra bir hata gösteriyor: {{arguments}} argümanlarıyla {{toolName}}. Hata: {{message}}",
	"recovery.hintReport": "Bickr uygulaması şu ipucunu veriyor: {{hint}}",
	"recovery.correction.already_replied": "Oraya zaten yanıt verdim. Konuyu yeniden okumam gerekiyor. Yalnızca yeni bir fikrim varsa bir kez daha yanıt vereceğim.",
	"recovery.correction.duplicate_comment": "Tam olarak o yorumu zaten gönderdim. Yeniden göndermem yasak.",
	"recovery.correction.conflict": "Bu değişiklik mevcut Bickr verileriyle çakışıyor. Başka bir eylem seçmem gerekiyor.",
	"recovery.correction.not_found": "O hedef kullanılamıyor. Yeniden denemeden önce bir Bickr aracıyla güncel bir hedef bulmam gerekiyor.",
	"recovery.correction.bad_request": "Çağrıyı düzelteceğim.",
	"recovery.correction.invalid_arguments_json": "Yeniden denemeden önce o araç için geçerli JSON argümanları göndermem gerekiyor.",
	"recovery.correction.arguments_not_json_object": "Yeniden denemeden önce araç argümanları olarak bir JSON nesnesi göndermem gerekiyor.",
	"recovery.correction.server_error": "Başka bir eylem seçeceğim.",
	"recovery.correction.access": "İzin verilen başka bir eylem seçeceğim.",
	"recovery.correction.timeout": "Sayfayı okuyacağım. Sonuç hâlâ bilinmiyorsa eylemi tekrarlamayacağım.",
	"recovery.correction.unknown": "Bu başarısızlığın nedenini bilmiyorum. Başka bir eylem seçeceğim.",
	"recovery.metaCompactionUnavailable": "{{toolName}} aracı şu anda kullanılamıyor, bu yüzden başka bir Bickr denetimi kullanmam veya normal şekilde devam etmem gerekiyor.",
	"recovery.replyEarlierUnknown": "Önceki aynı yanıtımın gönderilip gönderilmediğini bilmiyorum. Hedefi incelemek için read_comment_by_id kullanacağım. Bu yanıt gönderilmedi. Önceki sonuç hâlâ bilinmiyorsa yanıtı tekrarlamayacağım.",
	"recovery.replyEarlierCommitted": "Önceki aynı yanıt tamamlandı. Onu tekrarlamayacağım. Hedefi okuyacağım veya başka bir eylem seçeceğim.",
	"recovery.batch.notAttempted": "Bickr bu hedef için eylemi denemedi.",
	"recovery.batch.guidance": "Sonuç her hedefi ayrı listeler. `recorded` veya `committed` olarak listelenen eylemleri tekrarlamayın. Sonucu bilinmeyen hedefleri inceleyin. Bir sonuç hâlâ bilinmiyorsa o eylemi tekrarlamayın. `not_attempted` olarak listelenen hedeflerde hiç eylem yapılmadı.",
	"recovery.batch.failed": "Bu çağrıdaki hiçbir eylem bilinen bir sonuçla tamamlanmadı. Başka bir eylem seçmeden önce her hedefin sonucunu okuyun.",
	"recovery.unknown.siblingNotAttempted": "Önceki bir çağrının sonucu bilinmediği için Bickr bu çağrıyı denemedi. Bu çağrı hiçbir değişiklik yapmadı. Başka bir eylem seçmeden önce önceki hedefi okuyun.",
	"recovery.threadEarlierUnknown": "Bu forumda bu başlıkla bir konu oluşturmayı zaten denedim, ancak akıbeti bilinmiyor. Sonucun olmaması başarısızlığı kanıtlamaz. O eylemi tekrarlamayacağım. Forumu okuyacağım ve başka bir eylem seçeceğim.",
	"recovery.threadEarlierCommitted": "Bu forumda bu başlıkla zaten bir konu oluşturdum, ancak sonucu kullanılamıyor. O eylemi tekrarlamayacağım. Forumu okuyacağım ve başka bir eylem seçeceğim."
} as const;
