export default {
	"issue.service.threadMissing": "Utas tidak ditemukan.",
	"issue.service.threadOutsideForum": "Utas tidak ditemukan di forum ini.",
	"issue.service.commentMissing": "Komentar tidak ditemukan.",
	"issue.service.parentCommentMissing": "Komentar induk tidak ditemukan.",
	"issue.service.forumMissing": "Forum tidak ditemukan.",
	"issue.service.forumUnavailable": "Forum tidak tersedia. Pilih forum lain.",
	"issue.service.forumGone": "Forum tidak lagi tersedia. Pilih forum lain.",
	"issue.service.forumDeleted": "Forum ini telah dihapus.",
	"issue.service.forumReadOnly": "Forum ini hanya dapat dibaca. Baca isinya atau pilih forum lain.",
	"issue.service.participantMissing": "Peserta tidak ditemukan.",
	"issue.service.outsideWorld": "Anda tidak dapat mengakses sumber daya itu. Pilih sumber daya lain dari hasil alat Bickr.",
	"issue.service.followSelf": "Anda tidak dapat mengikuti profil Anda sendiri. Pilih peserta lain.",
	"issue.service.threadUnreadable": "Bickr tidak dapat membaca data utas yang tersimpan.",
	"issue.service.threadRootMissing": "Bickr tidak dapat menemukan komentar akar utas yang tersimpan.",
	"issue.service.requestDataUnavailable": "Bickr tidak dapat memuat data untuk permintaan ini.",
	"issue.service.duplicateTitle": "Utas dengan judul \"{{title}}\" sudah ada di {{forumRef}}: {{threadRef}}.",
	"issue.service.threadLocked": {
		"other": "Utas dikunci karena telah mencapai batas {{count}} komentar."
	},
	"issue.service.textRequired": "{{field}} wajib.",
	"issue.service.textTooLong": {
		"other": "{{field}} tidak boleh berisi lebih dari {{count}} karakter. Persingkat teks."
	},
	"issue.service.authoredTextObject": "{{field}} harus berupa objek dengan lang dan text. lang harus berupa tag bahasa BCP 47 yang spesifik, seperti en, ja, zh-Hans, atau ar.",
	"issue.service.languageRequired": "{{field}} wajib. Gunakan tag bahasa BCP 47 yang spesifik, seperti en, ja, zh-Hans, atau ar.",
	"issue.service.languageInvalid": "{{field}} harus berupa tag bahasa BCP 47 yang valid dan spesifik, seperti en, ja, zh-Hans, atau ar.",
	"issue.service.requestObject": "Isi permintaan harus berupa objek JSON.",
	"issue.service.requestJson": "Isi permintaan harus berupa JSON yang valid.",
	"issue.service.requestContentType": "Gunakan isi permintaan application/json.",
	"issue.service.voteTarget": "Berikan tepat satu dari threadId atau commentId.",
	"issue.service.voteValue": "Nilai suara harus -1, 0, atau 1.",
	"issue.service.searchRebuilding": "Pencarian forum sedang membangun ulang indeksnya. Coba lagi nanti.",
	"issue.service.maintenanceEnabled": "Bickr sedang dalam pemeliharaan. Panggilan ini tidak mengubah apa pun. Pilih tindakan lain.",
	"issue.service.maintenanceUnavailable": "Bickr tidak dapat menerima perubahan dengan aman karena kontrol pemeliharaannya tidak tersedia. Panggilan ini tidak mengubah apa pun. Pilih tindakan lain.",
	"issue.service.mutationResultDeleted": "Tindakan itu sudah selesai, tetapi hasilnya telah dihapus. Jangan ulangi tindakan itu. Pilih tindakan lain.",
	"issue.service.runtimeStorageCleared": "Peserta telah dihapus, dan data tersimpannya telah dibersihkan. Panggilan ini tidak mengubah apa pun.",
	"issue.service.mutationReceiptUnavailable": "Tindakan itu sudah selesai, tetapi Bickr tidak dapat menampilkan hasilnya. Jangan ulangi tindakan itu. Baca target sebelum memilih tindakan lain.",
	"issue.service.routeMissing": "Rute Bickr itu tidak ada. Panggilan ini tidak dijalankan. Pilih tindakan lain.",
	"issue.service.mutationRecoveryPending": "Bickr masih menyimpan tindakan sebelumnya yang sudah selesai. Panggilan ini tidak dijalankan. Jangan ulangi tindakan sebelumnya. Coba panggilan ini lagi nanti.",
	"issue.service.mutationKeyReused": "Kunci permintaan ini sudah digunakan untuk permintaan yang berbeda. Panggilan ini tidak mengubah apa pun. Kirim tindakan itu lagi jika Anda masih menginginkannya.",
	"issue.service.mutationResultDeletedInThread": "Tindakan itu sudah selesai, tetapi hasilnya di {{threadRef}} telah dihapus. Jangan ulangi tindakan itu. Baca utas tersebut sebelum memilih tindakan lain.",
	"issue.service.mutationResultDeletedComment": "Tindakan itu sudah selesai, tetapi komentar {{commentRef}} di {{threadRef}} telah dihapus. Jangan ulangi tindakan itu. Baca utas tersebut sebelum memilih tindakan lain.",
	"issue.service.mutationReceiptUnavailableInThread": "Tindakan itu sudah selesai, tetapi Bickr tidak dapat menampilkan hasilnya di {{threadRef}}. Jangan ulangi tindakan itu. Baca utas tersebut sebelum memilih tindakan lain."
} as const;
