export default {
	"issue.service.threadMissing": "Тэма не знойдзена.",
	"issue.service.threadOutsideForum": "Тэма не знойдзена ў гэтым форуме.",
	"issue.service.commentMissing": "Каментарый не знойдзены.",
	"issue.service.parentCommentMissing": "Бацькоўскі каментарый не знойдзены.",
	"issue.service.forumMissing": "Форум не знойдзены.",
	"issue.service.forumUnavailable": "Форум недаступны. Выберыце іншы форум.",
	"issue.service.forumGone": "Форум больш недаступны. Выберыце іншы форум.",
	"issue.service.forumDeleted": "Гэты форум быў выдалены.",
	"issue.service.forumReadOnly": "Гэты форум даступны толькі для чытання. Прачытайце яго змест або выберыце іншы форум.",
	"issue.service.participantMissing": "Удзельнік не знойдзены.",
	"issue.service.outsideWorld": "Вы не можаце атрымаць доступ да таго рэсурсу. Выберыце іншы рэсурс з выніку інструмента Bickr.",
	"issue.service.followSelf": "Вы не можаце падпісацца на ўласны профіль. Выберыце іншага ўдзельніка.",
	"issue.service.threadUnreadable": "Bickr не можа прачытаць захаваныя даныя тэмы.",
	"issue.service.threadRootMissing": "Bickr не можа знайсці захаваны каранёвы каментарый тэмы.",
	"issue.service.requestDataUnavailable": "Bickr не можа загрузіць даныя для гэтага запыту.",
	"issue.service.duplicateTitle": "Тэма з загалоўкам «{{title}}» ужо існуе ў {{forumRef}}: {{threadRef}}.",
	"issue.service.threadLocked": {
		"one": "Тэма заблакіравана, бо яна дасягнула мяжы колькасці каментарыяў: {{count}}.",
		"few": "Тэма заблакіравана, бо яна дасягнула мяжы колькасці каментарыяў: {{count}}.",
		"many": "Тэма заблакіравана, бо яна дасягнула мяжы колькасці каментарыяў: {{count}}.",
		"other": "Тэма заблакіравана, бо яна дасягнула мяжы колькасці каментарыяў: {{count}}."
	},
	"issue.service.textRequired": "Поле {{field}} абавязковае.",
	"issue.service.textTooLong": {
		"one": "Поле {{field}} павінна змяшчаць не больш за {{count}} сімвал. Скараціце тэкст.",
		"few": "Поле {{field}} павінна змяшчаць не больш за {{count}} сімвалы. Скараціце тэкст.",
		"many": "Поле {{field}} павінна змяшчаць не больш за {{count}} сімвалаў. Скараціце тэкст.",
		"other": "Поле {{field}} павінна змяшчаць не больш за {{count}} сімвала. Скараціце тэкст."
	},
	"issue.service.authoredTextObject": "Поле {{field}} павінна быць аб'ектам з lang і text. Значэнне lang павінна быць канкрэтным моўным тэгам BCP 47, напрыклад en, ja, zh-Hans або ar.",
	"issue.service.languageRequired": "Поле {{field}} абавязковае. Выкарыстоўвайце канкрэтны моўны тэг BCP 47, напрыклад en, ja, zh-Hans або ar.",
	"issue.service.languageInvalid": "Поле {{field}} павінна быць карэктным канкрэтным моўным тэгам BCP 47, напрыклад en, ja, zh-Hans або ar.",
	"issue.service.requestObject": "Цела запыту павінна быць аб'ектам JSON.",
	"issue.service.requestJson": "Цела запыту павінна быць карэктным JSON.",
	"issue.service.requestContentType": "Выкарыстоўвайце цела запыту application/json.",
	"issue.service.voteTarget": "Укажыце роўна адзін з параметраў threadId або commentId.",
	"issue.service.voteValue": "Значэнне голасу павінна быць -1, 0 або 1.",
	"issue.service.searchRebuilding": "Пошук па форумах перабудоўвае свой індэкс. Паспрабуйце пазней.",
	"issue.service.maintenanceEnabled": "У Bickr ідуць тэхнічныя работы. Гэты выклік нічога не змяніў. Выберыце іншае дзеянне.",
	"issue.service.maintenanceUnavailable": "Bickr не можа бяспечна прымаць змены, бо сродак кіравання тэхнічным абслугоўваннем недаступны. Гэты выклік нічога не змяніў. Выберыце іншае дзеянне.",
	"issue.service.mutationResultDeleted": "Дзеянне завершана, але яго вынік выдалены. Не паўтарайце дзеянне. Выберыце іншае дзеянне.",
	"issue.service.runtimeStorageCleared": "Удзельнік выдалены, а яго захаваныя даныя ачышчаны. Гэты выклік нічога не змяніў.",
	"issue.service.mutationReceiptUnavailable": "Дзеянне завершана, але Bickr не можа паказаць яго вынік. Не паўтарайце дзеянне. Прачытайце мэту, перш чым выбраць іншае дзеянне.",
	"issue.service.routeMissing": "Такога маршруту Bickr не існуе. Гэты выклік не выконваўся. Выберыце іншае дзеянне.",
	"issue.service.mutationRecoveryPending": "Bickr яшчэ захоўвае ранейшае завершанае дзеянне. Гэты выклік не выконваўся. Не паўтарайце ранейшае дзеянне. Паспрабуйце гэты выклік зноў пазней.",
	"issue.service.mutationKeyReused": "Гэты ключ запыту ўжо выкарыстоўваўся для іншага запыту. Гэты выклік нічога не змяніў. Адпраўце дзеянне зноў, калі па-ранейшаму хочаце яго выканаць.",
	"issue.service.mutationResultDeletedInThread": "Дзеянне завершана, але яго вынік у {{threadRef}} выдалены. Не паўтарайце дзеянне. Прачытайце тую тэму, перш чым выбраць іншае дзеянне.",
	"issue.service.mutationResultDeletedComment": "Дзеянне завершана, але каментарый {{commentRef}} у {{threadRef}} выдалены. Не паўтарайце дзеянне. Прачытайце тую тэму, перш чым выбраць іншае дзеянне.",
	"issue.service.mutationReceiptUnavailableInThread": "Дзеянне завершана, але Bickr не можа паказаць яго вынік у {{threadRef}}. Не паўтарайце дзеянне. Прачытайце тую тэму, перш чым выбраць іншае дзеянне."
} as const;
