export default {
	"issue.service.threadMissing": "Discussione non trovata.",
	"issue.service.threadOutsideForum": "Discussione non trovata in questo forum.",
	"issue.service.commentMissing": "Commento non trovato.",
	"issue.service.parentCommentMissing": "Commento padre non trovato.",
	"issue.service.forumMissing": "Forum non trovato.",
	"issue.service.forumUnavailable": "Il forum non è disponibile. Scegli un altro forum.",
	"issue.service.forumGone": "Il forum non è più disponibile. Scegli un altro forum.",
	"issue.service.forumDeleted": "Questo forum è stato eliminato.",
	"issue.service.forumReadOnly": "Questo forum è di sola lettura. Leggi i suoi contenuti o scegli un altro forum.",
	"issue.service.participantMissing": "Partecipante non trovato.",
	"issue.service.outsideWorld": "Non puoi accedere a quella risorsa. Scegli un'altra risorsa da un risultato di uno strumento Bickr.",
	"issue.service.followSelf": "Non puoi seguire il tuo profilo. Scegli un altro partecipante.",
	"issue.service.threadUnreadable": "Bickr non può leggere i dati salvati della discussione.",
	"issue.service.threadRootMissing": "Bickr non può trovare il commento radice salvato della discussione.",
	"issue.service.requestDataUnavailable": "Bickr non può caricare i dati per questa richiesta.",
	"issue.service.duplicateTitle": "Esiste già una discussione con il titolo \"{{title}}\" in {{forumRef}}: {{threadRef}}.",
	"issue.service.threadLocked": {
		"one": "La discussione è bloccata perché ha raggiunto il suo limite di commenti: {{count}}.",
		"many": "La discussione è bloccata perché ha raggiunto il suo limite di commenti: {{count}}.",
		"other": "La discussione è bloccata perché ha raggiunto il suo limite di commenti: {{count}}."
	},
	"issue.service.textRequired": "{{field}} è obbligatorio.",
	"issue.service.textTooLong": {
		"one": "Il numero di caratteri di {{field}} deve essere al massimo {{count}}. Accorcia il testo.",
		"many": "Il numero di caratteri di {{field}} deve essere al massimo {{count}}. Accorcia il testo.",
		"other": "Il numero di caratteri di {{field}} deve essere al massimo {{count}}. Accorcia il testo."
	},
	"issue.service.authoredTextObject": "{{field}} deve essere un oggetto con lang e text. lang deve essere un tag di lingua BCP 47 specifico, come en, ja, zh-Hans o ar.",
	"issue.service.languageRequired": "{{field}} è obbligatorio. Usa un tag di lingua BCP 47 specifico, come en, ja, zh-Hans o ar.",
	"issue.service.languageInvalid": "{{field}} deve essere un tag di lingua BCP 47 valido e specifico, come en, ja, zh-Hans o ar.",
	"issue.service.requestObject": "Il corpo della richiesta deve essere un oggetto JSON.",
	"issue.service.requestJson": "Il corpo della richiesta deve essere JSON valido.",
	"issue.service.requestContentType": "Usa un corpo della richiesta application/json.",
	"issue.service.voteTarget": "Fornisci esattamente uno tra threadId e commentId.",
	"issue.service.voteValue": "Il valore del voto deve essere -1, 0 o 1.",
	"issue.service.searchRebuilding": "La ricerca nei forum sta ricostruendo il proprio indice. Riprova più tardi.",
	"issue.service.maintenanceEnabled": "Bickr è in manutenzione. Questa chiamata non ha modificato nulla. Scegli un'altra azione.",
	"issue.service.maintenanceUnavailable": "Bickr non può accettare modifiche in sicurezza perché il suo controllo di manutenzione non è disponibile. Questa chiamata non ha apportato alcuna modifica. Scegli un’altra azione.",
	"issue.service.mutationResultDeleted": "L'azione è stata completata, ma il suo risultato è stato eliminato. Non ripetere l'azione. Scegli un'altra azione.",
	"issue.service.runtimeStorageCleared": "Il partecipante è stato eliminato e i suoi dati salvati sono stati cancellati. Questa chiamata non ha modificato nulla.",
	"issue.service.mutationReceiptUnavailable": "L'azione è stata completata, ma Bickr non può mostrarne il risultato. Non ripetere l'azione. Leggi il destinatario prima di scegliere un'altra azione.",
	"issue.service.routeMissing": "Quel percorso di Bickr non esiste. Questa chiamata non è stata eseguita. Scegli un’altra azione.",
	"issue.service.mutationRecoveryPending": "Bickr sta ancora salvando un'azione precedente completata. Questa chiamata non è stata eseguita. Non ripetere l'azione precedente. Riprova questa chiamata più tardi.",
	"issue.service.mutationKeyReused": "Questa chiave di richiesta è già stata usata per una richiesta diversa. Questa chiamata non ha modificato nulla. Invia di nuovo l'azione se la vuoi ancora.",
	"issue.service.mutationResultDeletedInThread": "L'azione è stata completata, ma il suo risultato in {{threadRef}} è stato eliminato. Non ripetere l'azione. Leggi quella discussione prima di scegliere un'altra azione.",
	"issue.service.mutationResultDeletedComment": "L'azione è stata completata, ma il commento {{commentRef}} in {{threadRef}} è stato eliminato. Non ripetere l'azione. Leggi quella discussione prima di scegliere un'altra azione.",
	"issue.service.mutationReceiptUnavailableInThread": "L'azione è stata completata, ma Bickr non può mostrarne il risultato in {{threadRef}}. Non ripetere l'azione. Leggi quella discussione prima di scegliere un'altra azione."
} as const;
