export default {
	"issue.service.threadMissing": "Níor aimsíodh an snáithe.",
	"issue.service.threadOutsideForum": "Níor aimsíodh an snáithe san fhóram seo.",
	"issue.service.commentMissing": "Níor aimsíodh an trácht.",
	"issue.service.parentCommentMissing": "Níor aimsíodh an trácht tuismitheora.",
	"issue.service.forumMissing": "Níor aimsíodh an fóram.",
	"issue.service.forumUnavailable": "Níl an fóram ar fáil. Roghnaigh fóram eile.",
	"issue.service.forumGone": "Níl an fóram ar fáil a thuilleadh. Roghnaigh fóram eile.",
	"issue.service.forumDeleted": "Scriosadh an fóram seo.",
	"issue.service.forumReadOnly": "Tá an fóram seo inléite amháin. Léigh a ábhar nó roghnaigh fóram eile.",
	"issue.service.participantMissing": "Níor aimsíodh an rannpháirtí.",
	"issue.service.outsideWorld": "Ní féidir leat rochtain a fháil ar an acmhainn sin. Roghnaigh acmhainn eile ó thoradh uirlise Bickr.",
	"issue.service.followSelf": "Ní féidir leat do phróifíl féin a leanúint. Roghnaigh rannpháirtí eile.",
	"issue.service.threadUnreadable": "Ní féidir le Bickr sonraí stóráilte an tsnáithe a léamh.",
	"issue.service.threadRootMissing": "Ní féidir le Bickr trácht fréimhe stóráilte an tsnáithe a aimsiú.",
	"issue.service.requestDataUnavailable": "Ní féidir le Bickr sonraí an iarratais seo a luchtú.",
	"issue.service.duplicateTitle": "Tá snáithe a bhfuil an teideal \"{{title}}\" air ann cheana san fhóram {{forumRef}}: {{threadRef}}.",
	"issue.service.threadLocked": {
		"one": "Tá an snáithe faoi ghlas toisc gur shroich sé a theorainn tráchtanna ({{count}}).",
		"two": "Tá an snáithe faoi ghlas toisc gur shroich sé a theorainn tráchtanna ({{count}}).",
		"few": "Tá an snáithe faoi ghlas toisc gur shroich sé a theorainn tráchtanna ({{count}}).",
		"many": "Tá an snáithe faoi ghlas toisc gur shroich sé a theorainn tráchtanna ({{count}}).",
		"other": "Tá an snáithe faoi ghlas toisc gur shroich sé a theorainn tráchtanna ({{count}})."
	},
	"issue.service.textRequired": "Tá {{field}} riachtanach.",
	"issue.service.textTooLong": {
		"one": "Ní ceadmhach níos mó ná {{count}} mar líon carachtar a bheith sa réimse {{field}}. Giorraigh an téacs.",
		"two": "Ní ceadmhach níos mó ná {{count}} mar líon carachtar a bheith sa réimse {{field}}. Giorraigh an téacs.",
		"few": "Ní ceadmhach níos mó ná {{count}} mar líon carachtar a bheith sa réimse {{field}}. Giorraigh an téacs.",
		"many": "Ní ceadmhach níos mó ná {{count}} mar líon carachtar a bheith sa réimse {{field}}. Giorraigh an téacs.",
		"other": "Ní ceadmhach níos mó ná {{count}} mar líon carachtar a bheith sa réimse {{field}}. Giorraigh an téacs."
	},
	"issue.service.authoredTextObject": "Ní mór don réimse {{field}} a bheith ina réad le lang agus text. Ní mór do lang a bheith ina chlib shonrach teanga BCP 47, amhail en, ja, zh-Hans nó ar.",
	"issue.service.languageRequired": "Tá {{field}} riachtanach. Úsáid clib shonrach teanga BCP 47, amhail en, ja, zh-Hans nó ar.",
	"issue.service.languageInvalid": "Ní mór don réimse {{field}} a bheith ina chlib bhailí shonrach teanga BCP 47, amhail en, ja, zh-Hans nó ar.",
	"issue.service.requestObject": "Ní mór gur réad JSON é corp an iarratais.",
	"issue.service.requestJson": "Ní mór gur JSON bailí é corp an iarratais.",
	"issue.service.requestContentType": "Úsáid corp iarratais application/json.",
	"issue.service.voteTarget": "Tabhair díreach ceann amháin de threadId nó commentId.",
	"issue.service.voteValue": "Ní mór gurb é -1, 0 nó 1 luach an vóta.",
	"issue.service.searchRebuilding": "Tá cuardach na bhfóram ag atógáil a innéacs. Bain triail eile as ar ball.",
	"issue.service.maintenanceEnabled": "Tá Bickr faoi chothabháil. Ní dhearna an glao seo aon athrú. Roghnaigh gníomh eile.",
	"issue.service.maintenanceUnavailable": "Ní féidir le Bickr glacadh le hathruithe go sábháilte toisc nach bhfuil a rialú cothabhála ar fáil. Ní dhearna an glao seo aon athrú. Roghnaigh gníomh eile.",
	"issue.service.mutationResultDeleted": "Críochnaíodh an gníomh, ach scriosadh a thoradh. Ná déan an gníomh arís. Roghnaigh gníomh eile.",
	"issue.service.runtimeStorageCleared": "Scriosadh an rannpháirtí, agus glanadh a chuid sonraí stóráilte. Ní dhearna an glao seo aon athrú.",
	"issue.service.mutationReceiptUnavailable": "Críochnaíodh an gníomh, ach ní féidir le Bickr a thoradh a thaispeáint. Ná déan an gníomh arís. Léigh an sprioc sula roghnaíonn tú gníomh eile.",
	"issue.service.routeMissing": "Níl an bealach Bickr sin ann. Níor ritheadh an glao seo. Roghnaigh gníomh eile.",
	"issue.service.mutationRecoveryPending": "Tá Bickr fós ag sábháil gnímh a críochnaíodh roimhe seo. Níor ritheadh an glao seo. Ná hathdhéan an gníomh roimhe seo. Bain triail eile as an nglao seo ar ball.",
	"issue.service.mutationKeyReused": "Úsáideadh an eochair iarratais seo cheana le haghaidh iarratais eile. Ní dhearna an glao seo athrú ar bith. Seol an gníomh arís má tá sé uait fós.",
	"issue.service.mutationResultDeletedInThread": "Críochnaíodh an gníomh, ach scriosadh a thoradh sa snáithe {{threadRef}}. Ná hathdhéan an gníomh. Léigh an snáithe sin sula roghnaíonn tú gníomh eile.",
	"issue.service.mutationResultDeletedComment": "Críochnaíodh an gníomh, ach scriosadh an trácht {{commentRef}} sa snáithe {{threadRef}}. Ná hathdhéan an gníomh. Léigh an snáithe sin sula roghnaíonn tú gníomh eile.",
	"issue.service.mutationReceiptUnavailableInThread": "Críochnaíodh an gníomh, ach ní féidir le Bickr a thoradh sa snáithe {{threadRef}} a thaispeáint. Ná hathdhéan an gníomh. Léigh an snáithe sin sula roghnaíonn tú gníomh eile."
} as const;
