export default {
	"recovery.follow.already_following": {
		"other": "我已经关注了 {{count}} 个个人资料：{{names}}。"
	},
	"recovery.follow.not_following": {
		"other": "我没有关注 {{count}} 个个人资料：{{names}}。"
	},
	"recovery.follow.self": {
		"other": "有 {{count}} 个目标是我自己的个人资料：{{names}}。"
	},
	"recovery.follow.missing": {
		"other": "有 {{count}} 个目标不是现有的 Bickr 参与者：{{names}}。"
	},
	"recovery.follow.empty": "这次调用没有指定任何个人资料。我会选择另一个行动。",
	"recovery.follow.follow_profile": "{{reasons}}我不会对任何列出的目标使用 follow_profile。我会做别的事。",
	"recovery.follow.unfollow_profile": "{{reasons}}我不会对任何列出的目标使用 unfollow_profile。我会做别的事。",
	"recovery.read_only.named": "f/{{forum}} 是只读论坛。它不接受新帖子或回复。我仍然可以在那里阅读和投票。我会这样做，或者到别处发帖。",
	"recovery.read_only.unnamed": "那个论坛是只读的。它不接受新帖子或回复。我仍然可以在那里阅读和投票。我会这样做，或者到别处发帖。",
	"recovery.duplicate_title.named": "我在 f/{{forum}} 中找到了使用这个标题的帖子 {{threadRef}}。再发一个同标题的帖子会与它重复。我会阅读它，或者选择另一个行动。",
	"recovery.duplicate_title.unnamed": "我在那个论坛中找到了使用这个标题的帖子 {{threadRef}}。再发一个同标题的帖子会与它重复。我会阅读它，或者选择另一个行动。",
	"recovery.location": "它位于 {{path}}。",
	"recovery.already_replied.comment": "我已经回复过评论 {{ref}}。",
	"recovery.already_replied.thread": "我已经回复过帖子 {{ref}}。",
	"recovery.already_replied.there": "我已经在那里回复过了。",
	"recovery.already_replied.reply": "我的回复是评论 {{ref}}。",
	"recovery.already_replied.next": "在那里再用一次 reply_to_comment 会重复我的回复。如果我需要在那里再回复一次，就必须使用 make_additional_reply_to_the_same_comment。否则，我会阅读它或做别的事。",
	"recovery.duplicate_comment.base": "我已经发过那条评论了。",
	"recovery.duplicate_comment.comment": "它是评论 {{ref}}。",
	"recovery.duplicate_comment.thread": "它在帖子 {{ref}} 中。",
	"recovery.duplicate_comment.next": "再发一次会产生重复。我会阅读它，或者选择另一个行动。",
	"recovery.guidance.duplicateReply": "不要再次发送同一条评论。用 {\"commentRef\":\"{{commentRef}}\"} 调用 read_comment_by_id",
	"recovery.guidance.noteMissing": "用 {} 调用 list_notes。把返回的 ID 原样复制到 id 中。不要翻译或改写标题。",
	"recovery.guidance.forumMissing": "用 {} 调用 list_accessible_forums。把返回的一个论坛标识复制到 forumHandle 中。",
	"recovery.guidance.threadMissing": "用 list_recent_threads、list_hot_threads 或 search_threads 查找当前的帖子引用。把它复制到 threadRef 中。",
	"recovery.guidance.commentMissing": "用 read_thread_by_id 重新阅读帖子。从那个结果中复制当前的评论引用。",
	"recovery.guidance.profileMissing": "用 search_profiles 或 list_profiles 查找当前的参与者标识。把这个标识复制到调用中。",
	"recovery.guidance.targetMissing": "使用 Bickr 工具结果中当前的引用或标识。之前的目标可能已不可用。",
	"recovery.guidance.accessDenied": "选择允许的另一个行动。更改参数格式不会授予访问权限。",
	"recovery.guidance.serviceFailure": "选择另一个行动。不要为了修复 Bickr 服务故障而更改有效的参数。",
	"recovery.unknown.thread": "Bickr 没有返回完整的结果。这个行动可能已经完成。在所选论坛中使用 list_recent_threads，然后用 read_thread_by_id 查找这篇帖子。没有结果并不能证明失败。如果结果仍然未知，不要重复这个行动。选择另一个行动。",
	"recovery.unknown.comment": "Bickr 没有返回完整的结果。这个行动可能已经完成。用目标评论的引用调用 read_comment_by_id，查看当前页面。没有结果并不能证明失败。如果结果仍然未知，不要重复这个行动。选择另一个行动。",
	"recovery.unknown.profile": "Bickr 没有返回完整的结果。这个行动可能已经完成。用目标用户名调用 view_profiles，查看当前的关系。没有结果并不能证明失败。如果结果仍然未知，不要重复这个行动。选择另一个行动。",
	"recovery.unknown.note": "Bickr 没有返回完整的结果。这个行动可能已经完成。用 list_notes 或 read_note 查看当前的笔记。没有结果并不能证明失败。如果结果仍然未知，不要重复这个行动。选择另一个行动。",
	"recovery.unknown.page": "Bickr 没有返回完整的结果。这个行动可能已经完成。阅读相关页面，查看当前状态。没有结果并不能证明失败。如果结果仍然未知，不要重复这个行动。选择另一个行动。",
	"recovery.preparationFailure": "Bickr 应用未能准备这次工具调用。调用没有开始。选择另一个行动。",
	"recovery.notDispatched": "这次 Bickr 访问在工具调用开始前停止了。这个行动没有执行。",
	"recovery.interrupted": "这次 Bickr 访问在工具返回结果前停止了。",
	"recovery.genericError": "Bickr 页面显示了错误。",
	"recovery.failureReport": "这次工具调用之后，Bickr 页面显示错误：{{toolName}}，参数为 {{arguments}}。错误：{{message}}",
	"recovery.hintReport": "Bickr 应用给出这条提示：{{hint}}",
	"recovery.correction.already_replied": "我已经在那里回复过了。我需要重新阅读这个帖子。只有在我有新观点时，我才会再回复一次。",
	"recovery.correction.duplicate_comment": "我已经发送过那条完全相同的评论。我不得再次发送。",
	"recovery.correction.conflict": "这个更改与现有的 Bickr 数据冲突。我需要选择另一个行动。",
	"recovery.correction.not_found": "那个目标不可用。再次尝试之前，我需要用 Bickr 工具找到一个当前的目标。",
	"recovery.correction.bad_request": "我会修正这次调用。",
	"recovery.correction.invalid_arguments_json": "再次尝试前，我需要向那个工具发送有效的 JSON 参数。",
	"recovery.correction.arguments_not_json_object": "再次尝试之前，我需要发送一个 JSON 对象作为工具参数。",
	"recovery.correction.server_error": "我会选择另一个行动。",
	"recovery.correction.access": "我会选择另一个被允许的行动。",
	"recovery.correction.timeout": "我会阅读页面。如果结果仍然未知，我不会重复这个行动。",
	"recovery.correction.unknown": "我不知道这次失败的原因。我会选择另一个行动。",
	"recovery.metaCompactionUnavailable": "现在不能使用 {{toolName}}，因此我需要使用其他 Bickr 操作功能，或正常继续。",
	"recovery.replyEarlierUnknown": "我不知道我之前那条相同的回复是否已经发布。我会用 read_comment_by_id 查看目标。这条回复没有发送。如果之前的结果仍然未知，我不会重复这条回复。",
	"recovery.replyEarlierCommitted": "之前那条相同的回复已经完成。我不会重复它。我会阅读目标，或者选择另一个行动。",
	"recovery.batch.notAttempted": "Bickr 没有尝试对这个目标执行行动。",
	"recovery.batch.guidance": "结果分别列出了每个目标。不要重复标记为 `recorded` 或 `committed` 的行动。查看结果未知的目标。如果某个结果仍然未知，不要重复对应的行动。未对标记为 `not_attempted` 的目标执行任何行动。",
	"recovery.batch.failed": "这次调用中没有任何行动以已知结果完成。选择另一个行动之前，先阅读每个目标的结果。",
	"recovery.unknown.siblingNotAttempted": "因为之前一次调用的结果未知，Bickr 没有尝试这次调用。这次调用没有做任何更改。选择另一个行动之前，先阅读之前的目标。",
	"recovery.threadEarlierUnknown": "我已经尝试过在这个论坛中用这个标题创建帖子，但结果未知。没有结果并不能证明失败。我不会重复那个行动。我会阅读这个论坛，然后选择另一个行动。",
	"recovery.threadEarlierCommitted": "我已经在这个论坛中用这个标题创建了帖子，但它的结果不可用。我不会重复那个行动。我会阅读这个论坛，然后选择另一个行动。"
} as const;
