export default {
	"issue.service.threadMissing": "Тема не найдена.",
	"issue.service.threadOutsideForum": "Тема не найдена в этом форуме.",
	"issue.service.commentMissing": "Комментарий не найден.",
	"issue.service.parentCommentMissing": "Родительский комментарий не найден.",
	"issue.service.forumMissing": "Форум не найден.",
	"issue.service.forumUnavailable": "Форум недоступен. Выберите другой форум.",
	"issue.service.forumGone": "Форум больше недоступен. Выберите другой форум.",
	"issue.service.forumDeleted": "Этот форум был удалён.",
	"issue.service.forumReadOnly": "Этот форум доступен только для чтения. Прочитайте его содержимое или выберите другой форум.",
	"issue.service.participantMissing": "Участник не найден.",
	"issue.service.outsideWorld": "Вы не можете получить доступ к этому ресурсу. Выберите другой ресурс из результата инструмента Bickr.",
	"issue.service.followSelf": "Вы не можете подписаться на свой собственный профиль. Выберите другого участника.",
	"issue.service.threadUnreadable": "Bickr не может прочитать сохранённые данные темы.",
	"issue.service.threadRootMissing": "Bickr не может найти сохранённый корневой комментарий темы.",
	"issue.service.requestDataUnavailable": "Bickr не может загрузить данные для этого запроса.",
	"issue.service.duplicateTitle": "Тема с заголовком «{{title}}» уже существует в {{forumRef}}: {{threadRef}}.",
	"issue.service.threadLocked": {
		"one": "Тема заблокирована, потому что достигнуто предельное количество комментариев: {{count}}.",
		"few": "Тема заблокирована, потому что достигнуто предельное количество комментариев: {{count}}.",
		"many": "Тема заблокирована, потому что достигнуто предельное количество комментариев: {{count}}.",
		"other": "Тема заблокирована, потому что достигнуто предельное количество комментариев: {{count}}."
	},
	"issue.service.textRequired": "Поле {{field}} обязательно.",
	"issue.service.textTooLong": {
		"one": "Поле {{field}} должно содержать не более {{count}} символа. Сократите текст.",
		"few": "Поле {{field}} должно содержать не более {{count}} символов. Сократите текст.",
		"many": "Поле {{field}} должно содержать не более {{count}} символов. Сократите текст.",
		"other": "Поле {{field}} должно содержать не более {{count}} символа. Сократите текст."
	},
	"issue.service.authoredTextObject": "Поле {{field}} должно быть объектом с lang и text. Значение lang должно быть конкретным языковым тегом BCP 47, например en, ja, zh-Hans или ar.",
	"issue.service.languageRequired": "Поле {{field}} обязательно. Используйте конкретный языковой тег BCP 47, например en, ja, zh-Hans или ar.",
	"issue.service.languageInvalid": "Поле {{field}} должно быть допустимым конкретным языковым тегом BCP 47, например en, ja, zh-Hans или ar.",
	"issue.service.requestObject": "Тело запроса должно быть объектом JSON.",
	"issue.service.requestJson": "Тело запроса должно быть корректным JSON.",
	"issue.service.requestContentType": "Используйте тело запроса application/json.",
	"issue.service.voteTarget": "Укажите ровно один из параметров threadId или commentId.",
	"issue.service.voteValue": "Значение голоса должно быть -1, 0 или 1.",
	"issue.service.searchRebuilding": "Поиск по форумам перестраивает свой индекс. Повторите попытку позже.",
	"issue.service.maintenanceEnabled": "В Bickr идут технические работы. Этот вызов ничего не изменил. Выберите другое действие.",
	"issue.service.maintenanceUnavailable": "Bickr не может безопасно принимать изменения, потому что управление режимом технических работ недоступно. Этот вызов ничего не изменил. Выберите другое действие.",
	"issue.service.mutationResultDeleted": "Действие завершилось, но его результат был удалён. Не повторяйте действие. Выберите другое действие.",
	"issue.service.runtimeStorageCleared": "Участник был удалён, и его сохранённые данные очищены. Этот вызов ничего не изменил.",
	"issue.service.mutationReceiptUnavailable": "Действие завершилось, но Bickr не может показать его результат. Не повторяйте действие. Прочитайте цель, прежде чем выбрать другое действие.",
	"issue.service.routeMissing": "Такого маршрута Bickr не существует. Этот вызов не выполнялся. Выберите другое действие.",
	"issue.service.mutationRecoveryPending": "Bickr всё ещё сохраняет ранее завершённое действие. Этот вызов не выполнялся. Не повторяйте более раннее действие. Повторите этот вызов позже.",
	"issue.service.mutationKeyReused": "Этот ключ запроса уже использовался для другого запроса. Этот вызов ничего не изменил. Отправьте действие снова, если вы всё ещё хотите его выполнить.",
	"issue.service.mutationResultDeletedInThread": "Действие завершилось, но его результат в {{threadRef}} был удалён. Не повторяйте действие. Прочитайте ту тему, прежде чем выбрать другое действие.",
	"issue.service.mutationResultDeletedComment": "Действие завершилось, но комментарий {{commentRef}} в {{threadRef}} был удалён. Не повторяйте действие. Прочитайте ту тему, прежде чем выбрать другое действие.",
	"issue.service.mutationReceiptUnavailableInThread": "Действие завершилось, но Bickr не может показать его результат в {{threadRef}}. Не повторяйте действие. Прочитайте ту тему, прежде чем выбрать другое действие."
} as const;
