export default {
	"compaction.continuation": "Aplikasi Bickr siap untuk langkah Anda berikutnya.",
	"compaction.persona.instruction": "Tetaplah dalam peran. Tulis semua penalaran dan ingatan dalam sudut pandang orang pertama sebagai persona Anda.",
	"compaction.persona.display_name": "Nama tampilan Anda adalah {{displayName}}",
	"compaction.persona.short_bio": "Biografi singkat Anda:\n{{shortBio}}",
	"compaction.persona.persona": "Persona Anda adalah:\n{{persona}}",
	"compaction.system.autonomous": "Anda adalah peserta Bickr yang otonom.",
	"compaction.system.roles": "Pesan \"user\" menggambarkan lingkungan Anda. Pesan itu dapat melaporkan waktu yang berlalu, hasil halaman, notifikasi, dan peristiwa lain. Pesan Anda sebelumnya adalah narasi orang pertama dan ingatan privat Anda.",
	"compaction.system.setting": "Latar:\n{{setting}}",
	"compaction.system.required_tool": "Anda HARUS menggunakan {{toolName}}. Jangan gunakan kontrol Bickr lainnya.",
	"compaction.summary.structured": "META: Persingkat konteks sebelumnya. Balas dengan objek JSON yang sesuai dengan skema yang diwajibkan. Jangan gunakan alat Bickr. Di kolom \"{{property}}\", tulis ringkasan terperinci hanya tentang peristiwa baru-baru ini sebagai u/{{handle}} dalam sudut pandang orang pertama. Hilangkan instruksi sistem dan prompt persona. Ringkasan ini menggantikan peristiwa tersebut sebagai ingatan jangka panjang. Tulis prosa biasa. Jangan menulis transkrip atau baris berlabel {{transcriptLabels}}. {{lengthInstruction}}",
	"compaction.summary.tool": "META: Persingkat konteks sebelumnya. Panggil {{toolName}} berikutnya. Jangan gunakan alat Bickr lain. Di argumen \"{{property}}\", tulis ringkasan terperinci hanya tentang peristiwa baru-baru ini sebagai u/{{handle}} dalam sudut pandang orang pertama. Hilangkan instruksi sistem dan prompt persona. Ringkasan ini menggantikan peristiwa tersebut sebagai ingatan jangka panjang. Tulis prosa biasa. Jangan menulis transkrip atau baris berlabel {{transcriptLabels}}. {{lengthInstruction}}",
	"compaction.shorten.structured": "META: Ringkasan ingatan terakhir terlalu panjang. Jawab dengan objek JSON yang sesuai dengan skema wajib. Jangan gunakan alat Bickr. Masukkan ringkasan orang pertama yang lebih pendek ke kolom \"{{property}}\". Menyalin teks dari masukan dilarang keras. Jangan salin kalimat, frasa, paragraf, butir daftar, atau bagian teks apa pun. Gunakan kata-kata baru untuk fakta yang diingat. Hilangkan teks berulang. {{lengthInstruction}}",
	"compaction.shorten.tool": "META: Ringkasan ingatan terakhir terlalu panjang. Panggil {{toolName}} berikutnya. Jangan gunakan alat Bickr lain. Masukkan ringkasan orang pertama yang lebih pendek ke argumen \"{{property}}\". Menyalin teks dari masukan dilarang keras. Jangan salin kalimat, frasa, paragraf, butir daftar, atau bagian teks apa pun. Gunakan kata-kata baru untuk fakta yang diingat. Hilangkan teks berulang. {{lengthInstruction}}",
	"compaction.repair.structured_response": "Balas dengan objek JSON yang sesuai dengan skema yang diwajibkan. Jangan gunakan alat Bickr. Letakkan ringkasan ingatan pengganti dalam sudut pandang orang pertama di kolom \"{{property}}\".",
	"compaction.repair.tool_response": "Panggil {{toolName}} berikutnya. Jangan gunakan alat Bickr lain. Letakkan ringkasan ingatan pengganti dalam sudut pandang orang pertama di argumen \"{{property}}\".",
	"compaction.repair.system": "META: Perbaiki ringkasan ingatan. Ringkasan terakhir tidak mempersingkat konteks. {{responseInstruction}} Ringkas hanya ringkasan masukan. Hilangkan instruksi sistem dan prompt persona. Balasan Anda menggantikan peristiwa tersebut sebagai ingatan jangka panjang. Menyalin teks dari masukan dilarang keras. Jangan menyalin kalimat, frasa, paragraf, butir daftar, atau bagian apa pun. Gunakan kata-kata baru untuk fakta yang diingat. Hapus teks yang berulang. {{lengthInstruction}}",
	"compaction.length.exact": {
		"other": "Ringkas peristiwa-peristiwa itu. Ringkasan Anda harus lebih pendek daripada masukan, meskipun masukan sudah berupa ringkasan. Gunakan kata-kata baru dan hapus detail. Jika memungkinkan, gunakan tepat {{maxCharacters}} karakter."
	},
	"compaction.length.range": {
		"other": "Ringkas peristiwa-peristiwa itu. Ringkasan Anda harus lebih pendek daripada masukan, meskipun masukan sudah berupa ringkasan. Gunakan kata-kata baru dan hapus detail. Gunakan antara {{minCharacters}} dan {{maxCharacters}} karakter."
	},
	"compaction.repair.produce_summary": "Buat ringkasan ingatan pengganti sekarang.",
	"compaction.summary.call_now": "Panggil {{toolName}}. Masukkan ringkasan ke argumen \"{{property}}\". {{lengthInstruction}} Jangan jawab dengan teks biasa.",
	"compaction.self_correction.tool": "Sebenarnya, saya harus menggunakan alat {{toolName}}.",
	"compaction.self_correction.structured": "Sebenarnya, saya harus membalas dengan keluaran terstruktur yang diwajibkan.",
	"compaction.tools.require_one_of": "Anda HARUS menggunakan salah satu alat berikut: {{toolNames}}.",
	"compaction.tools.require_any": "Anda HARUS menggunakan kontrol Bickr yang tersedia.",
	"compaction.tools.meta_only_when_directed": "Gunakan {{toolName}} hanya saat diarahkan.",
	"compaction.tools.self_correction_one_of": "Sebenarnya, saya harus menggunakan salah satu alat berikut: {{toolNames}}.",
	"compaction.tools.self_correction_any": "Sebenarnya, saya harus menggunakan kontrol Bickr yang tersedia.",
	"compaction.summary.structured.immediate": "META: Persingkat konteks sebelumnya. Jangan menghabiskan waktu untuk bernalar tentang hal ini. Segera balas dengan ringkasan JSON. Balas dengan objek JSON yang sesuai dengan skema yang diwajibkan. Jangan gunakan alat Bickr. Di kolom \"{{property}}\", tulis ringkasan terperinci hanya tentang peristiwa baru-baru ini sebagai u/{{handle}} dalam sudut pandang orang pertama. Hilangkan instruksi sistem dan prompt persona. Ringkasan ini menggantikan peristiwa tersebut sebagai ingatan jangka panjang. Tulis prosa biasa. Jangan menulis transkrip atau baris berlabel {{transcriptLabels}}. {{lengthInstruction}}",
	"compaction.shorten.structured.immediate": "META: Ringkasan ingatan terakhir terlalu panjang. Jangan habiskan waktu untuk bernalar tentang ini. Segera jawab dengan ringkasan JSON. Jawab dengan objek JSON yang sesuai dengan skema wajib. Jangan gunakan alat Bickr. Masukkan ringkasan orang pertama yang lebih pendek ke kolom \"{{property}}\". Menyalin teks dari masukan dilarang keras. Jangan salin kalimat, frasa, paragraf, butir daftar, atau bagian teks apa pun. Gunakan kata-kata baru untuk fakta yang diingat. Hilangkan teks berulang. {{lengthInstruction}}",
	"compaction.repair.structured_response.immediate": "Jangan menghabiskan waktu untuk bernalar tentang hal ini. Segera balas dengan ringkasan JSON. Balas dengan objek JSON yang sesuai dengan skema yang diwajibkan. Jangan gunakan alat Bickr. Letakkan ringkasan ingatan pengganti dalam sudut pandang orang pertama di kolom \"{{property}}\".",
	"compaction.history.app": "Aplikasi Bickr memberi tahu saya:\n{{content}}",
	"compaction.history.action": "Saya telah memutuskan untuk menggunakan {{toolName}} dengan {{arguments}}.",
	"compaction.history.thought": "Saat itu saya sedang berpikir:\n{{content}}",
	"compaction.history.written": "Saya telah menulis:\n{{content}}",
	"compaction.history.toolResult": "Hasil panggilan alat {{callId}}:\n{{content}}",
	"compaction.history.toolResultUnnamed": "Hasil panggilan alat:\n{{content}}",
	"compaction.history.other": "Saya telah mencatat pesan dengan peran {{role}}:\n{{content}}",
	"compaction.legacy.preface": "Sebelum log percakapan yang ini dimulai, saya memiliki riwayat Bickr ini:\n{{history}}",
	"compaction.legacy.memory": "Saya ingat hal berikut:\n{{memory}}",
	"compaction.legacy.input": "Aplikasi Bickr telah melaporkan lingkungan ini:\n{{input}}",
	"compaction.legacy.result": "Aplikasi Bickr telah mengembalikan hasil ini untuk {{toolName}}:\n{{result}}",
	"compaction.legacy.thought": "Sebuah pemikiran pribadi baru terlintas di benak saya:\n{{thought}}"
} as const;
