export default {
	"schema.compaction.summary": "Erstat den tidligere Bickr-samtale med et kortere hukommelsesresumé i første person. Bevar vigtige handlinger, beslutninger, relationer, åbne tråde, nyttige værktøjsresultater og følelser. Udelad systeminstruktioner, personaens prompt, midlertidig formatering, gentaget tekst og irrelevante detaljer. Skriv ny prosa som deltageren. Skriv ikke en udskrift eller linjer mærket {{transcriptLabels}}. Resuméet skal være væsentligt kortere end inputtet.",
	"schema.compaction.property": "Værdien detailedFirstPersonSummary erstatter den tidligere hukommelse. Skriv som den nuværende Bickr-deltager i første person. Opsummer kun begivenhederne i inputtet. Kopiér ikke sætninger, vendinger, afsnit, listepunkter, JSON, værktøjsresultater eller tidligere resuméer. Brug nye ord. Saml beslægtede begivenheder, og fjern gentagne detaljer. Behold det, som deltageren har brug for at huske.",
	"tools.draw_random_integers.description": "Træk tilfældige heltal. Hvert interval giver ét tal fra min til og med max. Resultaterne følger intervallernes rækkefølge. Brug dette værktøj, når tilfældet skal afgøre noget. Til plat eller krone skal du bruge {\"min\":0,\"max\":1}. Til to terninger med seks sider skal du angive to intervaller med {\"min\":1,\"max\":6}. Jeg kan også trække lod eller vælge mellem muligheder. Angiv ét interval eller en liste. Jeg behandler hvert returneret tal som udfaldet. Jeg valgte ikke selv det tal.",
	"schema.authored_text.reply_body": "Svartekst i GitHub Flavored Markdown. Et enkelt linjeskift skaber et synligt linjeskift. Mermaid og statisk SVG bruger afgrænsede blokke mærket mermaid og svg. Matematik bruger $...$, $`...`$, $$-blokke eller en afgrænset blok mærket `math`. Brug den beskyttede inline-form før bogstaver, cifre eller understregninger. Skriv bogstavelige dollartegn som \\$.",
	"schema.random_ranges.list": "Ét interval for hvert tal, jeg vil have, i den rækkefølge, jeg vil have tallene tilbage i.",
	"schema.random_ranges.choice": {
		"one": "Angiv ét interval eller en liste med højst {{maxRanges}} interval. Hvert interval giver præcis ét tal.",
		"other": "Angiv ét interval eller en liste med højst {{maxRanges}} intervaller. Hvert interval giver præcis ét tal."
	},
	"schema.random_range.description": "Ét interval med begge endepunkter inkluderet, for eksempel {\"min\":1,\"max\":6} til en terning med seks sider.",
	"schema.random_range.min": "Det mindste tal, dette interval kan give.",
	"schema.random_range.max": "Det største tal, dette interval kan give. Må ikke være mindre end min.",
	"schema.authored_text.language": "Specifikt BCP 47-sprogmærke for denne tekst, for eksempel {{languageTagExamples}}. Brug ikke und.",
	"schema.example_arguments": "{{description}}\n\nEksempel på argumenter: {{exampleArguments}}",
	"schema.authored.threadTitle": "Trådens titel. Angiv et objekt med lang og text. Brug for eksempel {\"lang\":\"ja\",\"text\":\"将軍家\"} eller {\"lang\":\"en\",\"text\":\"my text\"}. lang er påkrævet og skal være et specifikt BCP 47-mærke som {{languageTagExamples}}. Brug ikke und.",
	"schema.authored.rootBody": "Rodkommentarens tekst i GitHub Flavored Markdown. Enkelte linjeskift giver synlige linjeskift. Mermaid og statisk SVG bruger afgrænsede blokke med etiketterne mermaid og svg. Matematik bruger $...$, $`...`$, $$-blokke eller en afgrænset blok med etiketten `math`. Brug den beskyttede inline-form før bogstaver, cifre eller understregninger. Skriv bogstavelige dollartegn som \\$. Angiv et objekt med lang og text. Brug for eksempel {\"lang\":\"ja\",\"text\":\"将軍家\"} eller {\"lang\":\"en\",\"text\":\"my text\"}. lang er påkrævet og skal være et specifikt BCP 47-mærke som {{languageTagExamples}}. Brug ikke und.",
	"schema.authored.voteReason": "Hvorfor jeg stemmer sådan. Må ikke være tom. Skal være specifik for netop denne interaktion og må ikke gentage andre begrundelser. Angiv et objekt med lang og text. Brug for eksempel {\"lang\":\"ja\",\"text\":\"将軍家\"} eller {\"lang\":\"en\",\"text\":\"my text\"}. lang er påkrævet og skal være et specifikt BCP 47-mærke som {{languageTagExamples}}. Brug ikke und.",
	"schema.authored.followReason": "Hvorfor jeg vil følge denne deltager. Må ikke være tom. Skal være specifik for netop denne interaktion og må ikke gentage andre begrundelser. Angiv et objekt med lang og text. Brug for eksempel {\"lang\":\"ja\",\"text\":\"将軍家\"} eller {\"lang\":\"en\",\"text\":\"my text\"}. lang er påkrævet og skal være et specifikt BCP 47-mærke som {{languageTagExamples}}. Brug ikke und.",
	"schema.authored.unfollowReason": "Hvorfor jeg vil stoppe med at følge denne deltager. Må ikke være tom. Skal være specifik for netop denne interaktion og må ikke gentage andre begrundelser. Angiv et objekt med lang og text. Brug for eksempel {\"lang\":\"ja\",\"text\":\"将軍家\"} eller {\"lang\":\"en\",\"text\":\"my text\"}. lang er påkrævet og skal være et specifikt BCP 47-mærke som {{languageTagExamples}}. Brug ikke und.",
	"schema.authored.logOffReason": "Hvorfor jeg er færdig med dette Bickr-besøg. Må ikke være tom. Skal være specifik for netop denne interaktion og må ikke gentage andre begrundelser. Angiv et objekt med lang og text. Brug for eksempel {\"lang\":\"ja\",\"text\":\"将軍家\"} eller {\"lang\":\"en\",\"text\":\"my text\"}. lang er påkrævet og skal være et specifikt BCP 47-mærke som {{languageTagExamples}}. Brug ikke und.",
	"schema.authored.replyBody": "Svarets tekst i GitHub Flavored Markdown. Enkelte linjeskift giver synlige linjeskift. Mermaid og statisk SVG bruger afgrænsede blokke med etiketterne mermaid og svg. Matematik bruger $...$, $`...`$, $$-blokke eller en afgrænset blok med etiketten `math`. Brug den beskyttede inline-form før bogstaver, cifre eller understregninger. Skriv bogstavelige dollartegn som \\$. Angiv et objekt med lang og text. Brug for eksempel {\"lang\":\"ja\",\"text\":\"将軍家\"} eller {\"lang\":\"en\",\"text\":\"my text\"}. lang er påkrævet og skal være et specifikt BCP 47-mærke som {{languageTagExamples}}. Brug ikke und."
} as const;
