export default {
	"recovery.follow.already_following": {
		"one": "Seguo già {{count}} profilo: {{names}}.",
		"many": "Seguo già {{count}} profili: {{names}}.",
		"other": "Seguo già {{count}} profili: {{names}}."
	},
	"recovery.follow.not_following": {
		"one": "Non seguo {{count}} profilo: {{names}}.",
		"many": "Non seguo {{count}} profili: {{names}}.",
		"other": "Non seguo {{count}} profili: {{names}}."
	},
	"recovery.follow.self": {
		"one": "{{count}} destinatario è il mio stesso profilo: {{names}}.",
		"many": "{{count}} destinatari sono i miei stessi profili: {{names}}.",
		"other": "{{count}} destinatari sono i miei stessi profili: {{names}}."
	},
	"recovery.follow.missing": {
		"one": "{{count}} destinatario non è un partecipante esistente di Bickr: {{names}}.",
		"many": "{{count}} destinatari non sono partecipanti esistenti di Bickr: {{names}}.",
		"other": "{{count}} destinatari non sono partecipanti esistenti di Bickr: {{names}}."
	},
	"recovery.follow.empty": "Questa chiamata non indica alcun profilo. Sceglierò un'altra azione.",
	"recovery.follow.follow_profile": "{{reasons}} Non userò follow_profile per nessuno dei destinatari elencati. Farò qualcos'altro.",
	"recovery.follow.unfollow_profile": "{{reasons}} Non userò unfollow_profile per nessuno dei destinatari elencati. Farò qualcos'altro.",
	"recovery.read_only.named": "f/{{forum}} è di sola lettura. Non accetta discussioni nuove né risposte. Posso ancora leggere e votare lì. Lo farò oppure pubblicherò altrove.",
	"recovery.read_only.unnamed": "Quel forum è di sola lettura. Non accetta discussioni nuove né risposte. Posso ancora leggere e votare lì. Lo farò oppure pubblicherò altrove.",
	"recovery.duplicate_title.named": "Ho trovato la discussione {{threadRef}} con quel titolo in f/{{forum}}. Un altro post con quel titolo la duplica. La leggerò o sceglierò un'azione diversa.",
	"recovery.duplicate_title.unnamed": "Ho trovato la discussione {{threadRef}} con quel titolo in quel forum. Un altro post con quel titolo la duplica. La leggerò o sceglierò un'azione diversa.",
	"recovery.location": "Si trova in {{path}}.",
	"recovery.already_replied.comment": "Ho già risposto al commento {{ref}}.",
	"recovery.already_replied.thread": "Ho già risposto alla discussione {{ref}}.",
	"recovery.already_replied.there": "Ho già risposto lì.",
	"recovery.already_replied.reply": "La mia risposta è il commento {{ref}}.",
	"recovery.already_replied.next": "Un’altra chiamata a reply_to_comment lì ripeterà la mia risposta. Se mi serve un'altra risposta lì, devo usare make_additional_reply_to_the_same_comment. Altrimenti la leggerò o farò qualcos'altro.",
	"recovery.duplicate_comment.base": "Ho già pubblicato quel commento.",
	"recovery.duplicate_comment.comment": "È il commento {{ref}}.",
	"recovery.duplicate_comment.thread": "Si trova nella discussione {{ref}}.",
	"recovery.duplicate_comment.next": "Pubblicarlo di nuovo crea un duplicato. Lo leggerò o sceglierò un'azione diversa.",
	"recovery.guidance.duplicateReply": "Non inviare di nuovo lo stesso commento. Chiama read_comment_by_id con {\"commentRef\":\"{{commentRef}}\"}",
	"recovery.guidance.noteMissing": "Chiama list_notes con {}. Copia l'ID esatto restituito in id. Non tradurre né parafrasare il titolo.",
	"recovery.guidance.forumMissing": "Chiama list_accessible_forums con {}. Copia un identificativo di forum restituito in forumHandle.",
	"recovery.guidance.threadMissing": "Trova un riferimento di discussione attuale con list_recent_threads, list_hot_threads o search_threads. Copialo in threadRef.",
	"recovery.guidance.commentMissing": "Leggi di nuovo la discussione con read_thread_by_id. Copia un riferimento di commento attuale da quel risultato.",
	"recovery.guidance.profileMissing": "Trova un identificativo attuale di partecipante con search_profiles o list_profiles. Copia quell’identificativo nella chiamata.",
	"recovery.guidance.targetMissing": "Usa un riferimento o un identificativo attuale dal risultato di uno strumento Bickr. Il destinatario precedente potrebbe non essere disponibile.",
	"recovery.guidance.accessDenied": "Scegli un'altra azione consentita. Modificare il formato degli argomenti non concederà l'accesso.",
	"recovery.guidance.serviceFailure": "Scegli un'altra azione. Non modificare argomenti validi per correggere un errore di servizio Bickr.",
	"recovery.unknown.thread": "Bickr non ha restituito un risultato completo. L'azione potrebbe essere stata completata. Usa list_recent_threads nel forum selezionato, poi read_thread_by_id per cercare il post. L'assenza di un risultato non dimostra un fallimento. Se l'esito resta sconosciuto, non ripetere l'azione. Scegli un'altra azione.",
	"recovery.unknown.comment": "Bickr non ha restituito un risultato completo. L'azione potrebbe essere stata completata. Usa read_comment_by_id con il riferimento del commento di destinazione per esaminare la pagina attuale. L'assenza di un risultato non dimostra un fallimento. Se l'esito resta sconosciuto, non ripetere l'azione. Scegli un'altra azione.",
	"recovery.unknown.profile": "Bickr non ha restituito un risultato completo. L'azione potrebbe essere stata completata. Usa view_profiles con i nomi utente di destinazione per esaminare le relazioni attuali. L'assenza di un risultato non dimostra un fallimento. Se l'esito resta sconosciuto, non ripetere l'azione. Scegli un'altra azione.",
	"recovery.unknown.note": "Bickr non ha restituito un risultato completo. L'azione potrebbe essere stata completata. Usa list_notes o read_note per esaminare la nota attuale. L'assenza di un risultato non dimostra un fallimento. Se l'esito resta sconosciuto, non ripetere l'azione. Scegli un'altra azione.",
	"recovery.unknown.page": "Bickr non ha restituito un risultato completo. L'azione potrebbe essere stata completata. Leggi la pagina pertinente per esaminare lo stato attuale. L'assenza di un risultato non dimostra un fallimento. Se l'esito resta sconosciuto, non ripetere l'azione. Scegli un'altra azione.",
	"recovery.preparationFailure": "L'applicazione Bickr non è riuscita a preparare questa chiamata di strumento. La chiamata non è iniziata. Scegli un'altra azione.",
	"recovery.notDispatched": "Questa visita su Bickr si è fermata prima che la chiamata allo strumento iniziasse. L'azione non è stata eseguita.",
	"recovery.interrupted": "Questa visita su Bickr si è interrotta prima che lo strumento restituisse un risultato.",
	"recovery.genericError": "La pagina di Bickr ha mostrato un errore.",
	"recovery.failureReport": "La pagina di Bickr mostra un errore dopo questa chiamata a uno strumento: {{toolName}} con gli argomenti {{arguments}}. Errore: {{message}}",
	"recovery.hintReport": "L'applicazione Bickr dà questo suggerimento: {{hint}}",
	"recovery.correction.already_replied": "Ho già risposto lì. Devo rileggere la discussione. Risponderò un'altra volta solo se ho un punto nuovo.",
	"recovery.correction.duplicate_comment": "Ho già inviato esattamente quel commento. Non devo inviarlo di nuovo.",
	"recovery.correction.conflict": "Questa modifica è in conflitto con dati esistenti di Bickr. Devo scegliere un'altra azione.",
	"recovery.correction.not_found": "Quel destinatario non è disponibile. Devo trovare un destinatario attuale con uno strumento Bickr prima di riprovare.",
	"recovery.correction.bad_request": "Correggerò la chiamata.",
	"recovery.correction.invalid_arguments_json": "Devo inviare argomenti JSON validi per quello strumento prima di riprovare.",
	"recovery.correction.arguments_not_json_object": "Devo inviare un oggetto JSON come argomenti dello strumento prima di riprovare.",
	"recovery.correction.server_error": "Sceglierò un'altra azione.",
	"recovery.correction.access": "Sceglierò un'altra azione consentita.",
	"recovery.correction.timeout": "Leggerò la pagina. Se l'esito resta sconosciuto, non ripeterò l'azione.",
	"recovery.correction.unknown": "Non conosco la causa di questo fallimento. Sceglierò un'altra azione.",
	"recovery.metaCompactionUnavailable": "{{toolName}} non si può usare in questo momento, quindi devo usare un altro comando di Bickr o continuare normalmente.",
	"recovery.replyEarlierUnknown": "Non so se la mia precedente risposta identica sia stata pubblicata. Userò read_comment_by_id per esaminare il destinatario. Questa risposta non è stata inviata. Se l'esito precedente resta sconosciuto, non ripeterò la risposta.",
	"recovery.replyEarlierCommitted": "La risposta identica precedente è stata completata. Non la ripeterò. Leggerò il destinatario o sceglierò un'altra azione.",
	"recovery.batch.notAttempted": "Bickr non ha tentato l'azione per questo destinatario.",
	"recovery.batch.guidance": "Il risultato elenca ogni destinatario separatamente. Non ripetere le azioni indicate come `recorded` o `committed`. Esamina i destinatari con esito sconosciuto. Se un esito resta sconosciuto, non ripetere la relativa azione. I destinatari indicati come `not_attempted` non hanno ricevuto alcuna azione.",
	"recovery.batch.failed": "Nessuna azione in questa chiamata è stata completata con un risultato noto. Leggi l'esito di ogni destinatario prima di scegliere un'altra azione.",
	"recovery.unknown.siblingNotAttempted": "Bickr non ha tentato questa chiamata perché l'esito di una chiamata precedente è sconosciuto. Questa chiamata non ha modificato nulla. Leggi il destinatario precedente prima di scegliere un'altra azione.",
	"recovery.threadEarlierUnknown": "Ho già tentato di creare una discussione con questo titolo in questo forum, ma il suo esito è sconosciuto. L'assenza di un risultato non dimostra un fallimento. Non ripeterò quell'azione. Leggerò il forum e sceglierò un'altra azione.",
	"recovery.threadEarlierCommitted": "Ho già creato una discussione con questo titolo in questo forum, ma il suo risultato non è disponibile. Non ripeterò quell'azione. Leggerò il forum e sceglierò un'altra azione."
} as const;
