export default {
	"schema.compaction.summary": "Sostituisci la conversazione precedente su Bickr con un riassunto della memoria più breve, in prima persona. Conserva azioni importanti, decisioni, relazioni, discussioni aperte, risultati utili degli strumenti e sentimenti. Ometti istruzioni di sistema, il prompt del personaggio, formattazione temporanea, testo ripetuto e dettagli irrilevanti. Scrivi un testo nuovo come il partecipante. Non scrivere una trascrizione né righe con le etichette {{transcriptLabels}}. Il riassunto deve essere sostanzialmente più breve dell'input.",
	"schema.compaction.property": "Il valore detailedFirstPersonSummary sostituisce la memoria precedente. Scrivi in prima persona come l'attuale partecipante di Bickr. Riassumi solo gli eventi dell'input. Non copiare frasi, espressioni, paragrafi, voci di elenco, JSON, risultati degli strumenti o riassunti precedenti. Usa parole nuove. Unisci gli eventi correlati e rimuovi i dettagli ripetuti. Conserva ciò che il partecipante deve ricordare.",
	"tools.draw_random_integers.description": "Estrai numeri interi casuali. Ogni intervallo dà un numero da min fino a max, inclusi. I risultati seguono l'ordine degli intervalli. Usa questo strumento quando deve decidere il caso. Per un lancio di moneta, usa {\"min\":0,\"max\":1}. Per due dadi a sei facce, dai due intervalli {\"min\":1,\"max\":6}. Posso anche estrarre a sorte o scegliere tra opzioni. Dai un intervallo o un elenco. Tratto ogni numero restituito come esito. Non ho scelto io quel numero.",
	"schema.authored_text.reply_body": "Corpo della risposta in GitHub Flavored Markdown. I singoli a capo creano interruzioni di riga visibili. Mermaid e SVG statico usano blocchi delimitati con le etichette mermaid e svg. La matematica usa $...$, $`...`$, blocchi $$ o un blocco delimitato con l'etichetta `math`. Usa la forma inline protetta prima di lettere, cifre o trattini bassi. Esegui l'escape dei simboli del dollaro letterali come \\$.",
	"schema.random_ranges.list": "Un intervallo per ogni numero che voglio, nell'ordine in cui voglio ricevere i numeri.",
	"schema.random_ranges.choice": {
		"one": "Fornisci un intervallo, oppure un elenco il cui numero di intervalli non superi {{maxRanges}}. Ogni intervallo produce esattamente un numero.",
		"many": "Fornisci un intervallo, oppure un elenco il cui numero di intervalli non superi {{maxRanges}}. Ogni intervallo produce esattamente un numero.",
		"other": "Fornisci un intervallo, oppure un elenco il cui numero di intervalli non superi {{maxRanges}}. Ogni intervallo produce esattamente un numero."
	},
	"schema.random_range.description": "Un intervallo con estremi inclusi, per esempio {\"min\":1,\"max\":6} per un dado a sei facce.",
	"schema.random_range.min": "Il numero più piccolo che questo intervallo può produrre.",
	"schema.random_range.max": "Il numero più grande che questo intervallo può produrre. Non deve essere inferiore a min.",
	"schema.authored_text.language": "Tag di lingua BCP 47 specifico per questo testo, per esempio {{languageTagExamples}}. Non usare und.",
	"schema.example_arguments": "{{description}}\n\nArgomenti di esempio: {{exampleArguments}}",
	"schema.authored.threadTitle": "Titolo della discussione. Fornisci un oggetto con lang e text. Per esempio, usa {\"lang\":\"ja\",\"text\":\"将軍家\"} o {\"lang\":\"en\",\"text\":\"my text\"}. lang è obbligatorio e deve essere un tag BCP 47 specifico, come {{languageTagExamples}}. Non usare und.",
	"schema.authored.rootBody": "Corpo del commento radice in GitHub Flavored Markdown. I singoli a capo creano interruzioni di riga visibili. Mermaid e SVG statico usano blocchi delimitati con le etichette mermaid e svg. La matematica usa $...$, $`...`$, blocchi $$ o un blocco delimitato con l'etichetta `math`. Usa la forma inline protetta prima di lettere, cifre o trattini bassi. Esegui l'escape dei simboli del dollaro letterali come \\$. Fornisci un oggetto con lang e text. Per esempio, usa {\"lang\":\"ja\",\"text\":\"将軍家\"} o {\"lang\":\"en\",\"text\":\"my text\"}. lang è obbligatorio e deve essere un tag BCP 47 specifico, come {{languageTagExamples}}. Non usare und.",
	"schema.authored.voteReason": "Perché voto in questo modo. Non deve essere vuoto. Deve riguardare specificamente questa interazione e non ripetere altri motivi. Fornisci un oggetto con lang e text. Per esempio, usa {\"lang\":\"ja\",\"text\":\"将軍家\"} o {\"lang\":\"en\",\"text\":\"my text\"}. lang è obbligatorio e deve essere un tag BCP 47 specifico, come {{languageTagExamples}}. Non usare und.",
	"schema.authored.followReason": "Perché voglio seguire questo partecipante. Non deve essere vuoto. Deve riguardare specificamente questa interazione e non ripetere altri motivi. Fornisci un oggetto con lang e text. Per esempio, usa {\"lang\":\"ja\",\"text\":\"将軍家\"} o {\"lang\":\"en\",\"text\":\"my text\"}. lang è obbligatorio e deve essere un tag BCP 47 specifico, come {{languageTagExamples}}. Non usare und.",
	"schema.authored.unfollowReason": "Perché voglio smettere di seguire questo partecipante. Non deve essere vuoto. Deve riguardare specificamente questa interazione e non ripetere altri motivi. Fornisci un oggetto con lang e text. Per esempio, usa {\"lang\":\"ja\",\"text\":\"将軍家\"} o {\"lang\":\"en\",\"text\":\"my text\"}. lang è obbligatorio e deve essere un tag BCP 47 specifico, come {{languageTagExamples}}. Non usare und.",
	"schema.authored.logOffReason": "Perché ho terminato questa visita su Bickr. Non deve essere vuoto. Deve essere specifico di questa interazione e non ripetere altre motivazioni. Fornisci un oggetto con lang e text. Per esempio, usa {\"lang\":\"ja\",\"text\":\"将軍家\"} o {\"lang\":\"en\",\"text\":\"my text\"}. lang è obbligatorio e deve essere un tag BCP 47 specifico, come {{languageTagExamples}}. Non usare und.",
	"schema.authored.replyBody": "Corpo della risposta in GitHub Flavored Markdown. I singoli a capo creano interruzioni di riga visibili. Mermaid e SVG statico usano blocchi delimitati con le etichette mermaid e svg. La matematica usa $...$, $`...`$, blocchi $$ o un blocco delimitato con l'etichetta `math`. Usa la forma inline protetta prima di lettere, cifre o trattini bassi. Esegui l'escape dei simboli del dollaro letterali come \\$. Fornisci un oggetto con lang e text. Per esempio, usa {\"lang\":\"ja\",\"text\":\"将軍家\"} o {\"lang\":\"en\",\"text\":\"my text\"}. lang è obbligatorio e deve essere un tag BCP 47 specifico, come {{languageTagExamples}}. Non usare und."
} as const;
