/**
 * Deletion of the notifications a deleted comment or thread generated.
 *
 * Neither notification table has referential integrity with the content it
 * points at: `notifications` carries a formatted `source_object_id` and
 * `human_notifications` a raw `source_id`/`target_id` pair, and nothing ever
 * cleared either when the content died. A bot notification survives its source
 * with the source's full text embedded in its stored payload, so delivery
 * quotes a deleted comment back; a human notification survives as a row whose
 * link resolves to nothing.
 *
 * ## The invariant
 *
 * Retraction is keyed on the deleted object itself: what dies is what the
 * deleted comment or thread *generated*. A live reparented child's reply
 * notification quotes its former parent in `replyTo`, and that parent's deletion
 * leaves the quote behind. This is an accepted residual, not an oversight — the
 * child is alive and the notification is about the child, so retracting it would
 * retract notice of live content. Do not add dependency metadata to close it.
 *
 * ## Ref shapes
 *
 * The two tables store refs in different shapes, and binding one table's shape
 * against the other silently matches nothing:
 *
 * - `notifications.source_object_id` holds the formatted `c/<id>` or `t/<id>`
 *   ref, plus, on legacy rows, a bare `cmt_…`/`thr_…` id.
 * - `human_notifications` holds raw ids in `source_id`/`target_id`, never a
 *   formatted ref. A vote row's `source_id` is a composite
 *   `comment:<id>:<actor>` key that is deliberately not parsed here: the voted
 *   comment is reachable through the target arm, which is enough.
 *
 * Bare-id matching is limited to the `cmt_`/`thr_`-prefixed legacy ids. A modern
 * short content id is type-ambiguous — a thread's root comment id *equals* its
 * thread id (`rootCommentIdForThreadId`) — so a bare short id must never be
 * emitted as a match value. Matching is by exact `IN` value throughout, never
 * `LIKE`: `_` is a `LIKE` wildcard and every legacy prefix contains one.
 *
 * ## Shape of the helpers
 *
 * The helpers hand back prepared statements instead of running them, because
 * every caller folds them into the same `db.batch` that tombstones the content —
 * the notification deletes then land with the comment tombstones, the votes, and
 * the subscription deletes, or not at all. Every statement is an unconditional
 * `DELETE`, so a retried delete path is idempotent.
 *
 * They live in their own module for unit-testability of the chunking and
 * ref-format logic, and for symmetry with `human-subscriptions.ts`; unlike that
 * helper there is no import cycle to dodge, since every current caller is in
 * `social.ts`.
 *
 * ## KV
 *
 * Bot-side this deletes the D1 row only. A notification document whose row is
 * gone is invisible to every reader and expires on its own TTL — the invariant
 * `deleteDeliveredNotifications` in `social.ts` states — so there is nothing to
 * write to KV from inside a D1 batch. Bootstrap documents, the one TTL-free
 * shape, carry no content ref and are never selected here.
 */

import { formatCommentRef, formatThreadRef, type ContentRef } from "./ids";
import { chunks, d1SafeBoundParameters, type D1DatabaseLike, type D1PreparedStatementLike } from "./storage";

/**
 * A bot statement binds nothing but match values, so its chunk is the full
 * ceiling; a human statement spends one bind on the type column. Both are
 * counted in bindings rather than refs, because one ref can contribute two bot
 * match values.
 */
const maxBotMatchValuesPerStatement = d1SafeBoundParameters;
const maxHumanIdsPerStatement = d1SafeBoundParameters - 1;

/**
 * Every `source_object_id` value that would name this ref in `notifications`:
 * the formatted ref always, and the bare id only for a legacy prefixed one.
 */
function botMatchValues(ref: ContentRef): string[] {
	if (ref.type === "comment") {
		return ref.id.startsWith("cmt_") ? [formatCommentRef(ref.id), ref.id] : [formatCommentRef(ref.id)];
	}
	return ref.id.startsWith("thr_") ? [formatThreadRef(ref.id), ref.id] : [formatThreadRef(ref.id)];
}

function inPlaceholders(count: number): string {
	return Array.from({ length: count }, () => "?").join(", ");
}

/**
 * The statements that retract every notification generated by the given comments
 * and threads. Repeated refs collapse, so a caller may pass a list built from
 * overlapping sources — a thread and its own root comment, say — without paying
 * for the same delete twice; an empty ref set yields no statements at all.
 */
export function notificationSourceDeleteStatements(
	db: D1DatabaseLike,
	refs: readonly ContentRef[],
): D1PreparedStatementLike[] {
	const botMatches = new Set<string>();
	const idsByType = new Map<ContentRef["type"], Set<string>>();
	for (const ref of refs) {
		if (!ref.id) {
			continue;
		}
		for (const value of botMatchValues(ref)) {
			botMatches.add(value);
		}
		const existing = idsByType.get(ref.type);
		if (existing) {
			existing.add(ref.id);
			continue;
		}
		idsByType.set(ref.type, new Set([ref.id]));
	}

	const statements: D1PreparedStatementLike[] = [];
	for (const chunk of chunks([...botMatches], maxBotMatchValuesPerStatement)) {
		statements.push(
			db
				.prepare(`DELETE FROM notifications WHERE source_object_id IN (${inPlaceholders(chunk.length)})`)
				.bind(...chunk),
		);
	}
	for (const [type, ids] of idsByType) {
		for (const chunk of chunks([...ids], maxHumanIdsPerStatement)) {
			statements.push(
				db
					.prepare(
						`DELETE FROM human_notifications
						 WHERE source_type = ?
						   AND source_id IN (${inPlaceholders(chunk.length)})`,
					)
					.bind(type, ...chunk),
				db
					.prepare(
						`DELETE FROM human_notifications
						 WHERE target_type = ?
						   AND target_id IN (${inPlaceholders(chunk.length)})`,
					)
					.bind(type, ...chunk),
			);
		}
	}
	return statements;
}

/**
 * The same retraction for the arm that has no thread document to read: the
 * comment refs come from `comments_index` as a subquery rather than from a list.
 *
 * Ordering inside the caller's batch is immaterial. Tombstoning is an `UPDATE`
 * and these subqueries carry no `deleted_at` filter, so a comment row still
 * resolves whether it is tombstoned before or after these statements run.
 *
 * `substr` rather than `LIKE` for the legacy prefix, for the reason the module
 * comment gives: `_` is a `LIKE` wildcard.
 */
export function threadIndexScopedNotificationDeleteStatements(
	db: D1DatabaseLike,
	threadId: string,
): D1PreparedStatementLike[] {
	const commentRefsOfThread = `SELECT comment_id FROM comments_index WHERE thread_id = ?`;
	return [
		db
			.prepare(
				`DELETE FROM notifications
				 WHERE source_object_id IN (
					SELECT 'c/' || comment_id FROM comments_index WHERE thread_id = ?
					UNION ALL
					SELECT comment_id FROM comments_index WHERE thread_id = ? AND substr(comment_id, 1, 4) = 'cmt_'
				 )`,
			)
			.bind(threadId, threadId),
		db
			.prepare(
				`DELETE FROM human_notifications
				 WHERE source_type = 'comment'
				   AND source_id IN (${commentRefsOfThread})`,
			)
			.bind(threadId),
		db
			.prepare(
				`DELETE FROM human_notifications
				 WHERE target_type = 'comment'
				   AND target_id IN (${commentRefsOfThread})`,
			)
			.bind(threadId),
		...notificationSourceDeleteStatements(db, [{ type: "thread", id: threadId }]),
	];
}
