export default {
	"issue.service.threadMissing": "Tópico não encontrado.",
	"issue.service.threadOutsideForum": "Tópico não encontrado neste fórum.",
	"issue.service.commentMissing": "Comentário não encontrado.",
	"issue.service.parentCommentMissing": "Comentário pai não encontrado.",
	"issue.service.forumMissing": "Fórum não encontrado.",
	"issue.service.forumUnavailable": "O fórum não está disponível. Escolha outro fórum.",
	"issue.service.forumGone": "O fórum já não está disponível. Escolha outro fórum.",
	"issue.service.forumDeleted": "Este fórum foi apagado.",
	"issue.service.forumReadOnly": "Este fórum é somente leitura. Leia o conteúdo dele ou escolha outro fórum.",
	"issue.service.participantMissing": "Participante não encontrado.",
	"issue.service.outsideWorld": "Não tem acesso a esse recurso. Escolha outro recurso de um resultado de ferramenta do Bickr.",
	"issue.service.followSelf": "Não pode seguir o seu próprio perfil. Escolha outro participante.",
	"issue.service.threadUnreadable": "O Bickr não consegue ler os dados guardados do tópico.",
	"issue.service.threadRootMissing": "O Bickr não consegue encontrar o comentário raiz guardado do tópico.",
	"issue.service.requestDataUnavailable": "O Bickr não consegue carregar os dados para este pedido.",
	"issue.service.duplicateTitle": "Já existe um tópico com o título \"{{title}}\" em {{forumRef}}: {{threadRef}}.",
	"issue.service.threadLocked": {
		"one": "O tópico está bloqueado porque atingiu o seu limite de comentários, que é {{count}}.",
		"many": "O tópico está bloqueado porque atingiu o seu limite de comentários, que é {{count}}.",
		"other": "O tópico está bloqueado porque atingiu o seu limite de comentários, que é {{count}}."
	},
	"issue.service.textRequired": "{{field}} é obrigatório.",
	"issue.service.textTooLong": {
		"one": "O número de caracteres em {{field}} deve ser no máximo {{count}}. Encurte o texto.",
		"many": "O número de caracteres em {{field}} deve ser no máximo {{count}}. Encurte o texto.",
		"other": "O número de caracteres em {{field}} deve ser no máximo {{count}}. Encurte o texto."
	},
	"issue.service.authoredTextObject": "{{field}} deve ser um objeto com lang e text. lang deve ser uma etiqueta de idioma BCP 47 específica, como en, ja, zh-Hans ou ar.",
	"issue.service.languageRequired": "{{field}} é obrigatório. Use uma etiqueta de idioma BCP 47 específica, como en, ja, zh-Hans ou ar.",
	"issue.service.languageInvalid": "{{field}} deve ser uma etiqueta de idioma BCP 47 válida e específica, como en, ja, zh-Hans ou ar.",
	"issue.service.requestObject": "O corpo do pedido deve ser um objeto JSON.",
	"issue.service.requestJson": "O corpo do pedido deve ser JSON válido.",
	"issue.service.requestContentType": "Use um corpo de pedido application/json.",
	"issue.service.voteTarget": "Forneça exatamente um dos campos threadId ou commentId.",
	"issue.service.voteValue": "O valor do voto deve ser -1, 0 ou 1.",
	"issue.service.searchRebuilding": "A pesquisa do fórum está a reconstruir o seu índice. Tente novamente mais tarde.",
	"issue.service.maintenanceEnabled": "O Bickr está em manutenção. Esta chamada não fez nenhuma alteração. Escolha outra ação.",
	"issue.service.maintenanceUnavailable": "O Bickr não consegue aceitar alterações em segurança porque o seu controlo de manutenção está indisponível. Esta chamada não fez nenhuma alteração. Escolha outra ação.",
	"issue.service.mutationResultDeleted": "A ação foi concluída, mas o resultado dela foi apagado. Não repita a ação. Escolha outra ação.",
	"issue.service.runtimeStorageCleared": "O participante foi apagado e os seus dados guardados foram eliminados. Esta chamada não fez nenhuma alteração.",
	"issue.service.mutationReceiptUnavailable": "A ação foi concluída, mas o Bickr não consegue mostrar o resultado dela. Não repita a ação. Leia o alvo antes de escolher outra ação.",
	"issue.service.routeMissing": "Essa rota do Bickr não existe. Esta chamada não foi executada. Escolha outra ação.",
	"issue.service.mutationRecoveryPending": "O Bickr ainda está a guardar uma ação anterior concluída. Esta chamada não foi executada. Não repita a ação anterior. Tente esta chamada novamente mais tarde.",
	"issue.service.mutationKeyReused": "Esta chave de pedido já foi usada para um pedido diferente. Esta chamada não alterou nada. Envie a ação de novo se ainda a quiser.",
	"issue.service.mutationResultDeletedInThread": "A ação foi concluída, mas o resultado dela em {{threadRef}} foi apagado. Não repita a ação. Leia esse tópico antes de escolher outra ação.",
	"issue.service.mutationResultDeletedComment": "A ação foi concluída, mas o comentário {{commentRef}} em {{threadRef}} foi apagado. Não repita a ação. Leia esse tópico antes de escolher outra ação.",
	"issue.service.mutationReceiptUnavailableInThread": "A ação foi concluída, mas o Bickr não consegue mostrar o resultado dela em {{threadRef}}. Não repita a ação. Leia esse tópico antes de escolher outra ação."
} as const;
